'use client'
import {useCallback,useEffect,useState} from 'react'
import Link from 'next/link'
import AuthGate from '@/components/AuthGate'
import {supabase,requireAccess,requireWritableDeployment} from '@/lib/supabase'
type Connection={account_id:string;status:string;last_verified_at:string|null;last_read_at:string|null;last_error:string|null}
type SavedRead={id:string;kind:'listings'|'orders';status:string;page:number;result:{records:Array<{listing_id?:string;order_id?:string;title?:string|null}>;has_more:boolean;total_pages:number}|null;created_at:string}
function EbayConnection(){
 const [account,setAccount]=useState<string|null>(null),[connection,setConnection]=useState<Connection|null>(null),[reads,setReads]=useState<SavedRead[]>([]),[setup,setSetup]=useState(false),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const preview=process.env.NEXT_PUBLIC_APP_DEPLOYMENT_ENV==='preview'
 async function load(){await requireAccess();const [a,c,r,ready]=await Promise.all([supabase.from('resale_accounts').select('id').eq('marketplace','ebay').eq('username','paulbr-89'),supabase.from('resale_ebay_connections').select('account_id,status,last_verified_at,last_read_at,last_error'),supabase.from('resale_ebay_reads').select('id,kind,status,page,result,created_at').order('created_at',{ascending:false}).limit(8),supabase.rpc('resale_ebay_setup_status')]);if(a.error||c.error||r.error||ready.error)throw Error('Setup unavailable');return {account:a.data.length===1?a.data[0].id:null,connection:c.data[0]||null,reads:r.data as SavedRead[],setup:ready.data===true}}
 const show=useCallback((data:Awaited<ReturnType<typeof load>>)=>{setAccount(data.account);setConnection(data.connection);setReads(data.reads);setSetup(data.setup);setLoaded(true)},[])
 useEffect(()=>{let alive=true;void load().then(d=>{if(alive)show(d)}).catch(()=>{if(alive)setError('eBay setup is not available yet. Your existing inventory is unchanged.')});return()=>{alive=false}},[show])
 async function session(){requireWritableDeployment();await requireAccess();const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Sign in again');return session}
 async function connect(){if(!account||busy||!setup)return;setBusy(true);setError('');try{const s=await session();const enrolled=await supabase.rpc('resale_ebay_enroll',{p_account_id:account});if(enrolled.error)throw enrolled.error;const response=await fetch('/api/integrations/ebay/start',{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({account_id:account})});if(!response.ok)throw Error('Connection unavailable');const data=await response.json(),url=new URL(data.authorization_url);if(url.origin!=='https://auth.ebay.com'||url.pathname!=='/oauth2/authorize')throw Error('Unexpected response');window.location.assign(url.href)}catch{setError('eBay authorization did not start. Check developer setup and try again.');setBusy(false)}}
 async function readPage(kind:'listings'|'orders'){if(!account||busy)return;setBusy(true);setError('');try{const s=await session(),key=`ebay-read:${s.user.id}:${account}:${kind}`;let pending=sessionStorage.getItem(key);if(!pending){const end=new Date(Date.now()-180000),start=new Date(end.getTime()-7*86400000);pending=JSON.stringify({account_id:account,request_id:crypto.randomUUID(),kind,page:1,...(kind==='orders'?{from:start.toISOString(),to:end.toISOString()}:{})});sessionStorage.setItem(key,pending)}const response=await fetch('/api/integrations/ebay/read',{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:pending});if(!response.ok)throw Error('Read not confirmed');sessionStorage.removeItem(key);show(await load())}catch{setError('This read was not confirmed. The same request is saved in this tab; retry after checking the connection.')}finally{setBusy(false)}}
 async function pause(){if(!account||busy)return;setBusy(true);try{await session();const result=await supabase.rpc('resale_ebay_pause',{p_account_id:account});if(result.error)throw result.error;show(await load())}catch{setError('Pause not confirmed. Refresh and retry.')}finally{setBusy(false)}}
 const label=connection?.status==='connected'?'Seller verified':connection?.status==='deletion_pending'?'Privacy review pending':connection?.status==='paused'?'Paused':'Not connected'
 return <main className="wb-integration-page"><Link className="wb-text-button" href="/">← Back to resale studio</Link><header className="wb-integration-heading"><p className="wb-eyebrow">EBAY</p><h1>eBay connection</h1><p>Verify your seller account and read shop evidence into the tracker.</p></header>
 <div className="wb-note"><p>These checks do not publish, edit, end listings or mark inventory sold. The first read saves up to 50 records; it is not a full shop sync.</p></div>
 {error&&<p role="alert" className="wb-alert">{error}</p>}{!loaded&&!error&&<p role="status">Checking setup…</p>}
 {loaded&&<section className="wb-panel wb-integration-card"><div className="wb-section-heading"><h2>paulbr-89</h2><span className="wb-badge wb-badge-amber">{label}</span></div><div className="wb-integration-card-body">
 {!setup&&<p className="wb-note">Developer account recovery and the data deletion workflow must be verified before eBay can connect. Saved listing reports remain available in Marketplaces.</p>}
 <p>Seller verified: {connection?.last_verified_at?new Date(connection.last_verified_at).toLocaleString():'Not yet'}</p><p>Last page read: {connection?.last_read_at?new Date(connection.last_read_at).toLocaleString():'Not yet'}</p>
 {connection?.last_error&&<p className="wb-help">Needs attention: {connection.last_error.replaceAll('_',' ')}.</p>}
 <div className="wb-integration-actions"><button className="wb-button wb-button-primary" disabled={busy||preview||!setup||!account||connection?.status==='deletion_pending'} onClick={connect}>Connect eBay</button><button className="wb-button wb-button-secondary" disabled={busy||preview||connection?.status!=='connected'} onClick={()=>readPage('listings')}>Read first listing page</button><button className="wb-button wb-button-secondary" disabled={busy||preview||connection?.status!=='connected'} onClick={()=>readPage('orders')}>Read recent orders</button>{connection&&<button className="wb-text-button" disabled={busy||preview||connection.status!=='connected'} onClick={pause}>Pause reads</button>}</div></div></section>}
 {reads.map(read=><section className="wb-panel wb-integration-card" key={read.id}><h2>{read.kind==='listings'?'Active listing evidence':'Recent order evidence'}</h2><p>{read.status==='complete'?`${read.result?.records.length||0} records saved on page ${read.page}`:'Read needs retry'} · {new Date(read.created_at).toLocaleString()}</p>{read.result?.has_more&&<p className="wb-help">More pages remain. Ask Codex to finish the bounded read before treating coverage as complete.</p>}<details><summary>Saved records</summary><ul>{read.result?.records.map((r,index)=><li key={index}>{r.title||'Order evidence'} · {r.listing_id||r.order_id||'Identifier unavailable'}</li>)}</ul></details></section>)}
 <section className="wb-panel wb-integration-permission"><h2>Permission and privacy</h2><p>eBay’s base permission covers more than reads. This integration exposes only the three reviewed read methods and keeps tokens in the private server path. Buyer contact and address fields are discarded.</p><p className="wb-help">A deletion notice pauses this connection and removes its API read records and refresh token. Historical exports require a separate verified cleanup before erasure is complete.</p></section></main>
}
export default function Page(){return <AuthGate><EbayConnection/></AuthGate>}
