import { baseline, migrate } from './helpers.mjs'
import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { readFile } from 'node:fs/promises'
const db=await baseline()
const owner=randomUUID(), stranger=randomUUID(), genealogy=randomUUID()
await db.query('insert into auth.users values ($1),($2),($3)',[owner,stranger,genealogy])
await migrate(db)
await db.query("insert into private.memberships(user_id,area) values ($1,'resale'),($2,'genealogy')",[owner,genealogy])
async function role(name,id='') { await db.exec(`reset role; set role ${name}`); await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]) }
async function denied(fn,code='42501') { await assert.rejects(fn,e=>e.code===code) }
const payload={item_name:'Test garment',platform:'Vinted',sale_date:'2026-09-05',sale_price:25,platform_fee:2,item_cost:3,shipping_cost:4}
async function save(p=payload,id=randomUUID()) { return (await db.query('select (public.save_sale($1,$2::jsonb)).*',[id,JSON.stringify(p)])).rows[0] }
await role('anon')
for(const table of ['inventory','sales','expenses','resell_clothes','book_of_snippets','thoughts','sale_history','sales_summary'])
  await denied(()=>db.query(`select * from public.${table}`))
await denied(()=>save())
console.log('PASS signed-out access denied for tables, view and sale function')
await role('authenticated',stranger)
assert.equal((await db.query('select * from public.inventory')).rows.length,0)
await denied(()=>save())
await denied(()=>db.query("insert into private.memberships values ($1,'resale',now())",[stranger]))
await denied(()=>db.query("insert into public.inventory(item_name,item_cost) values ('blocked',0)"))
console.log('PASS unapproved signed-in account denied and cannot grant itself access')
await role('authenticated',owner)
const item=(await db.query("insert into public.inventory(item_name,item_cost,platforms,date_added) values ('Test garment',3,array['Vinted'],'2026-01-01') returning id")).rows[0].id
const linked={...payload,inventory_id:item}
const req=randomUUID(), sale=await save(linked,req)
assert.equal(sale.profit,'16.00')
assert.equal(sale.inventory_id,item)
assert.equal((await db.query('select status from public.inventory where id=$1',[item])).rows[0].status,'sold')
assert.equal((await save(linked,req)).id,sale.id)
assert.equal((await db.query('select count(*) from public.sales')).rows[0].count,1)
await denied(()=>save({...linked,sale_price:99},req),'22023')
await denied(()=>save(linked),'22023')
await denied(()=>db.query('delete from public.inventory where id=$1',[item]))
await denied(()=>db.query("update public.inventory set status='unlisted' where id=$1",[item]))
await denied(()=>db.query('update public.sales set sale_price=1 where id=$1',[sale.id]))
console.log('PASS atomic sale retains item; exact retries return same sale; duplicate sale and direct bypass denied')
const corrected=await save({...payload,id:sale.id,version:sale.version,reason:'Shipping receipt correction',shipping_cost:5})
assert.equal(corrected.profit,'15.00'); assert.equal(corrected.version,2)
await denied(()=>save({...payload,id:sale.id,version:1,reason:'stale'}),'40001')
assert.equal((await db.query('select count(*) from public.sale_history')).rows[0].count,2)
await denied(()=>db.query('delete from public.sale_history'))
const voided=await save({id:sale.id,version:2,void:true,reason:'Sale cancelled'})
assert.equal(voided.status,'Void')
assert.equal((await db.query('select status from public.inventory where id=$1',[item])).rows[0].status,'unlisted')
assert.equal((await db.query('select * from public.sales_summary')).rows.length,0)
await save(linked)
console.log('PASS versioned correction, immutable history, void and resale of retained item')
const source={...payload,source_system:'vinted:account-a',source_record_id:'order-1:line-1'}
await save(source)
await denied(()=>save(source),'23505')
await save({...source,source_system:'vinted:account-b'})
console.log('PASS source/account/record uniqueness; independent sources remain distinct')
// Force failure AFTER the sale and inventory writes. PostgreSQL must roll all of them back.
await role('postgres')
await db.exec(`create function private.test_failure() returns trigger language plpgsql as $$ begin raise exception 'injected failure'; end $$;
 create trigger injected_failure before insert on private.sale_requests for each row execute function private.test_failure();`)
await role('authenticated',owner)
const failureItem=(await db.query("insert into public.inventory(item_name,item_cost) values ('Rollback item',1) returning id")).rows[0].id
const before=(await db.query('select count(*) from public.sales')).rows[0].count
const failedReq=randomUUID(), failedPayload={...payload,inventory_id:failureItem}
await denied(()=>save(failedPayload,failedReq),'P0001')
assert.equal((await db.query('select count(*) from public.sales')).rows[0].count,before)
assert.equal((await db.query('select status from public.inventory where id=$1',[failureItem])).rows[0].status,'unlisted')
await role('postgres');await db.exec('drop trigger injected_failure on private.sale_requests')
await role('authenticated',owner);await save(failedPayload,failedReq)
console.log('PASS injected late failure rolls back sale, item and audit; retry succeeds once')
for(const bad of [-1,1.234,'NaN','Infinity']) await denied(()=>save({...payload,sale_price:bad}),'22023')
await role('postgres')
await db.exec(await readFile(new URL('../scripts/pause-sale-writes.sql',import.meta.url),'utf8'))
await role('authenticated',owner)
await denied(()=>save())
await role('postgres')
await db.exec(await readFile(new URL('../scripts/resume-sale-writes.sql',import.meta.url),'utf8'))
await role('authenticated',owner)
await save()
console.log('PASS emergency write pause and verified resume preserve read access')
await role('authenticated',stranger)
assert.equal((await db.query('select * from public.sales')).rows.length,0)
assert.equal((await db.query('select * from public.sales_summary')).rows.length,0)
await role('authenticated','')
await denied(()=>save())
await role('authenticated',genealogy)
assert.equal((await db.query('select * from public.sales')).rows.length,0)
await denied(()=>save())
await db.query("insert into public.book_of_snippets(name) values ('Synthetic research test')")
await role('authenticated',owner)
assert.equal((await db.query('select * from public.book_of_snippets')).rows.length,0)
await role('postgres');await db.query('delete from private.memberships where user_id=$1',[owner])
await role('authenticated',owner)
await denied(()=>save())
assert.equal((await db.query('select * from public.sales_summary')).rows.length,0)
console.log('PASS area separation and immediate membership revocation, including view')
await db.close()
