import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';import ts from 'typescript';import {JSDOM} from 'jsdom';import React,{act} from 'react';
const dom=new JSDOM('<div id="root"></div>',{url:'https://resell-tracker-beta.vercel.app'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});
const {createRoot}=await import('react-dom/client'),require=createRequire(import.meta.url);let saved=null,calls=[],failStart=false,failStep=false,hold=null;
const api={requireAccess:async()=>{},requireWritableDeployment:()=>{},supabase:{auth:{getSession:async()=>({data:{session:{user:{id:'member'},access_token:'synthetic'}}})},from:()=>{const q={select:()=>q,eq:()=>q,order:()=>q,limit:()=>q,maybeSingle:async()=>({data:structuredClone(saved),error:null})};return q},rpc:async()=>{saved.status='cancelled';return {error:null}}}};
globalThis.fetch=async(url,options)=>{const input=JSON.parse(options.body);calls.push(input);if(input.op==='listing_run_start'){if(!saved||saved.id!==input.run_id)saved={id:input.run_id,account_id:input.account_id,status:'running',pages_read:0,records_read:0,expected_pages:2,started_at:'2026-09-06T00:00:00Z',last_error:null,finished_at:null};if(failStart){failStart=false;throw Error('Lost response')}}else{if(hold){const wait=hold;hold=null;await wait}if(failStep){failStep=false;throw Error('Paused')}saved.pages_read++;saved.records_read++;if(saved.pages_read===2)saved.status='complete'}return Response.json({run:structuredClone(saved)})};
const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(new URL('../components/EbayListingRun.tsx',import.meta.url),'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText)(n=>n==='@/lib/supabase'?api:require(n),m,m.exports);
let root=createRoot(document.getElementById('root'));const C=m.exports.EbayListingRun;const render=(id='account')=>act(async()=>{root.render(React.createElement(C,{key:id,accountId:id,connected:true}));await new Promise(r=>setTimeout(r,0))});const button=t=>[...document.querySelectorAll('button')].find(x=>x.textContent===t);const click=t=>act(async()=>{assert(button(t),t);button(t).click();await new Promise(r=>setTimeout(r,0))});
await render();failStart=true;await click('Read active listings');const first=calls[0];assert(localStorage.getItem('ebay-listing-run:member:account'));failStep=true;await click('Read active listings');assert.deepEqual(calls[1],first);assert.equal(saved.pages_read,0);
await act(async()=>root.unmount());root=createRoot(document.getElementById('root'));await render();await click('Resume listing read');assert.equal(saved.status,'complete');assert.equal(calls.filter(c=>c.op==='listing_run_step').length,3);assert.match(document.body.textContent,/All returned pages/);assert.match(document.body.textContent,/missing items are not marked sold or ended/);
// An in-flight step may finish on its old account but cannot launch more calls after a switch.
saved=null;await act(async()=>root.unmount());root=createRoot(document.getElementById('root'));await render();let release;hold=new Promise(r=>release=r);await click('Read active listings');const n=calls.length;await act(async()=>root.unmount());root=createRoot(document.getElementById('root'));saved=null;await render('other-account');await act(async()=>{saved={id:first.run_id,account_id:'account',pages_read:0,records_read:0,status:'running'};release();await new Promise(r=>setTimeout(r,0))});assert.equal(calls.length,n);
await act(async()=>root.unmount());dom.window.close();console.log('PASS rendered eBay exact lost-start retry, reload resume, automatic pages, truthful partial/complete copy and unmount fencing');
