import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {hash,identity,listingPage,orderPage,tradingBody,signatureHeader,verifyNotification,CALLBACK,DELETION,SCOPE} from '../supabase/functions/resale-ebay-connect/provider.mjs';
import {start,callback,read,createServices,createHandler,deletion,listingRun} from '../supabase/functions/resale-ebay-connect/runtime.mjs';
const wrap=(call,s)=>`<${call}Response xmlns="urn:ebay:apis:eBLBaseComponents"><Ack>Success</Ack>${s}</${call}Response>`;
const self=(h='paulbr-89',id='synthetic-eias')=>wrap('GetUser',`<User><UserID>${h}</UserID><EIASToken>${id}</EIASToken><Email>private@example.test</Email></User>`);
const c={client_id:'synthetic-app',client_secret:'synthetic-secret',runame:'synthetic-RuName',callback:CALLBACK,deletion_endpoint:DELETION,expected_handle:'paulbr-89',trading_version:'1423',state_id:crypto.randomUUID(),seller_eias_sha256:hash('synthetic-eias')};
const tokens={access_token:'synthetic-access',token_type:'User Access Token',expires_in:7200,refresh_token:'synthetic-refresh',refresh_token_expires_in:86400};
const account=crypto.randomUUID(),member=crypto.randomUUID(),binding='a'.repeat(43);
test('own seller route never supplies expected username; unknown/duplicate/DTD identity rejects',()=>{const body=tradingBody('GetUser',{UserID:'someone-else'});assert(!body.includes('<UserID>'));assert(!body.includes('<ItemID>'));assert.deepEqual(identity(self()),{handle:'paulbr-89',eias_token:'synthetic-eias'});assert.throws(()=>identity('<!DOCTYPE x>'+self()));assert.throws(()=>identity(wrap('GetUser','<User><UserID>x</UserID></User>')));assert.throws(()=>tradingBody('EndItem'));});
test('OAuth uses RuName/base scope/random state and rejects another valid seller before token storage',async()=>{let saved=0;const calls=[];const s={user:async()=>member,rpc:async(n,a)=>{calls.push([n,a]);if(n.endsWith('complete')){saved++;return {status:'connected'}}return c;},ebayToken:async(cfg,args)=>{assert.equal(args.redirect_uri,c.runame);assert(!('code_verifier'in args));return tokens;},trading:async()=>self('different-seller')};const out=await start({account_id:account,browser_binding:binding},'Bearer member',s),url=new URL(out.authorization_url);assert.equal(url.searchParams.get('redirect_uri'),c.runame);assert.equal(url.searchParams.get('scope'),SCOPE);assert(!url.searchParams.has('code_challenge'));assert.match(calls[0][1].p_state_hash,/^[a-f0-9]{64}$/);await assert.rejects(()=>callback({state:binding,browser_binding:binding,code:'code'},s),/wrong_seller/);assert.equal(saved,0);s.trading=async()=>self();assert.equal((await callback({state:binding,browser_binding:binding,code:'code'},s)).status,'connected');assert.equal(saved,1);});
test('official eBay signed test vector verifies; tamper, unsafe key IDs and unknown algorithms fail',async()=>{const v=JSON.parse(await readFile(new URL('./fixtures/ebay-official-notification.json',import.meta.url)));const sig=signatureHeader(v.signature),out=verifyNotification(v.message,sig,v.response);assert.equal(out.event_id,v.message.notification.notificationId);assert(!JSON.stringify(out).includes('test_user'));const changed=structuredClone(v.message);changed.notification.data.eiasToken='changed';assert.throws(()=>verifyNotification(changed,sig,v.response),/invalid_signature/);assert.throws(()=>signatureHeader(Buffer.from(JSON.stringify({...sig,kid:'../../evil'})).toString('base64')));assert.throws(()=>verifyNotification(v.message,sig,{...v.response,digest:'SHA256'}));});
test('listing projection preserves exact ID/quantity/price and strips buyer/private copy',()=>{const xml=wrap('GetMyeBaySelling','<ActiveList><ItemArray><Item><ItemID>123456789012</ItemID><Title>Plain &amp; striped</Title><QuantityAvailable>1</QuantityAvailable><PrivateNotes>PRIVATE</PrivateNotes><SellingStatus><CurrentPrice currencyID="USD">22.00</CurrentPrice><HighBidder><UserID>PRIVATE</UserID></HighBidder></SellingStatus></Item></ItemArray><PaginationResult><TotalNumberOfPages>1</TotalNumberOfPages><TotalNumberOfEntries>1</TotalNumberOfEntries></PaginationResult></ActiveList>');const out=listingPage(xml,1);assert.equal(out.records[0].title,'Plain & striped');assert.equal(out.records[0].current_price.value,'22.00');assert(!JSON.stringify(out).includes('PRIVATE'));assert.equal(out.has_more,false);});
test('orders verify seller EIAS separately from buyer and preserve changing order IDs/paid time absence',()=>{const xml=wrap('GetOrders','<HasMoreOrders>false</HasMoreOrders><PaginationResult><TotalNumberOfPages>1</TotalNumberOfPages><TotalNumberOfEntries>1</TotalNumberOfEntries></PaginationResult><OrderArray><Order><OrderID>unpaid-id</OrderID><SellerUserID>paulbr-89</SellerUserID><SellerEIASToken>synthetic-eias</SellerEIASToken><EIASToken>BUYER</EIASToken><OrderStatus>Completed</OrderStatus><CheckoutStatus><Status>Complete</Status></CheckoutStatus><TransactionArray><Transaction><Item><ItemID>123456789012</ItemID><Title>Shirt</Title></Item><OrderLineItemID>123456789012-42</OrderLineItemID><QuantityPurchased>1</QuantityPurchased><Buyer><Email>BUYER</Email></Buyer></Transaction></TransactionArray></Order></OrderArray>');const seller={eias_sha256:c.seller_eias_sha256,handle:'paulbr-89'},out=orderPage(xml,1,seller);assert.equal(out.records[0].paid_at,null);assert.equal(out.records[0].lines[0].line_id,'123456789012-42');assert(!JSON.stringify(out).includes('BUYER'));assert.throws(()=>orderPage(xml,1,{...seller,eias_sha256:hash('other')}),/wrong_order_seller/);const paid=orderPage(xml.replace('unpaid-id','paid-id').replace('</OrderID>','</OrderID><ExtendedOrderID>paid-alias</ExtendedOrderID><PaidTime>2026-09-05T01:00:00Z</PaidTime>'),1,seller);assert.equal(paid.records[0].lines[0].line_id,out.records[0].lines[0].line_id);assert.equal(paid.records[0].extended_order_id,'paid-alias');});
test('actual service transport fixed hosts, OAuth form headers,204 RPC, no redirects',async()=>{const seen=[];const s=createServices({SUPABASE_URL:'https://synthetic.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'synthetic-admin',SUPABASE_ANON_KEY:'synthetic-public'},async(url,opts)=>{seen.push([url,opts]);return url.includes('/rpc/')?new Response(null,{status:204}):Response.json(tokens)});assert.equal(await s.rpc('resale_ebay_finish_read',{}),null);await s.ebayToken(c,{grant_type:'authorization_code',code:'a+b%/=',redirect_uri:c.runame});assert.equal(new URLSearchParams(seen[1][1].body).get('code'),'a+b%/=');assert.equal(seen[1][0],'https://api.ebay.com/identity/v1/oauth2/token');assert.equal(seen[1][1].redirect,'manual');});
test('cached exact read performs no provider calls; signedout request denied',async()=>{const result={status:'complete',result:{records:[]}},s={user:async()=>member,rpc:async()=>({cached:true,result}),ebayToken:()=>assert.fail()};assert.deepEqual(await read({account_id:account,request_id:crypto.randomUUID(),kind:'listings',page:1},'Bearer member',s),result);const denied=createHandler(createServices({SUPABASE_URL:'https://synthetic.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'synthetic',SUPABASE_ANON_KEY:'synthetic'},()=>assert.fail()));const r=await denied(new Request('https://edge.test',{method:'POST',body:JSON.stringify({op:'start',account_id:account,browser_binding:binding})}));assert.equal(r.status,401);});
test('deletion challenge uses exact registered endpoint; verified receipt contains only bounded audit hashes',async()=>{const v=JSON.parse(await readFile(new URL('./fixtures/ebay-official-notification.json',import.meta.url)));let saved;const s={rpc:async(n,a)=>{if(n.endsWith('_config'))return {...c,verification_token:'v'.repeat(32)};saved=a;},publicKey:async()=>v.response};assert.equal((await deletion({challenge_code:'abc'},s)).challengeResponse,hash('abc'+'v'.repeat(32)+DELETION));await deletion({message:v.message,signature:v.signature},s);assert.deepEqual(Object.keys(saved.p_notice).sort(),['event_at','event_id','subject_eias_sha256','subject_handle_sha256','subject_user_sha256']);});

test('buyer deletion requires typed immutable EIAS; ambiguous BuyerUserID cannot replace it',()=>{const seller={eias_sha256:hash('seller'),handle:'paulbr-89'};const xml=id=>wrap('GetOrders',`<HasMoreOrders>false</HasMoreOrders><PaginationResult><TotalNumberOfPages>1</TotalNumberOfPages><TotalNumberOfEntries>1</TotalNumberOfEntries></PaginationResult><OrderArray><Order><OrderID>synthetic</OrderID><SellerEIASToken>seller</SellerEIASToken><BuyerUserID>${id}</BuyerUserID></Order></OrderArray>`);for(const id of ['old-mutable-username','immutable-user-id-123'])assert.throws(()=>orderPage(xml(id),1,seller),/buyer_deletion_binding_unavailable/);const out=orderPage(xml('immutable-user-id-123').replace('</OrderID>','</OrderID><EIASToken>stable-buyer</EIASToken>'),1,seller);assert.deepEqual(out.deletion_subjects,[{eias_sha256:hash('stable-buyer')}]);assert(!JSON.stringify(out).includes('immutable-user-id-123'));});

test('listing run resumes SQL-selected completed page receipt and checkpoints only its saved ID',async()=>{const member=crypto.randomUUID(),run_id=crypto.randomUUID(),request={account_id:crypto.randomUUID(),request_id:crypto.randomUUID(),kind:'listings',page:2},calls=[];const s={user:async()=>member,rpc:async(n,a)=>{calls.push([n,a]);if(n==='resale_ebay_claim_listing_run')return {run:{id:run_id},request};if(n==='resale_ebay_claim_read')return {cached:true,result:{status:'complete'}};if(n==='resale_ebay_checkpoint_listing_run')return {id:run_id,status:'complete'};throw Error('unexpected')},trading:async()=>{throw Error('cached read must not call provider')}};const result=await listingRun({op:'listing_run_step',run_id,account_id:crypto.randomUUID(),page:99},'Bearer synthetic',s);assert.equal(result.run.status,'complete');assert.equal(calls[1][1].p_account_id,request.account_id);assert.equal(calls[1][1].p_page,2);assert.equal(calls[2][1].p_read_id,request.request_id);});
