import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),origin='https://resell-tracker-beta.vercel.app';
const code=ts.transpileModule(fs.readFileSync(new URL('../lib/ebay-server.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
function setup(){const calls=[],env={NEXT_PUBLIC_SUPABASE_URL:'https://synthetic.supabase.co'},context={exports:{},require,process:{env},Request,Response,URL,AbortSignal,fetch:async(url,options)=>{calls.push({url,options,input:JSON.parse(options.body)});return Response.json(JSON.parse(options.body).op==='start'?{authorization_url:'https://auth.ebay.com/oauth2/authorize?state=synthetic'}:{status:'connected',account_id:'synthetic-feed'});}};vm.runInNewContext(code,context);return {api:context.exports,calls,env};}
const start=(options={})=>new Request(`${origin}/api/integrations/ebay/start`,{method:'POST',headers:{Origin:origin,Authorization:'Bearer synthetic-member',...options.headers},body:JSON.stringify({account_id:'11111111-1111-4111-8111-111111111111'})});
test('start rejects cross-origin/signed-out/preview and forwards only member bearer plus random binding',async()=>{const {api,calls,env}=setup();assert.equal((await api.ebayStart(start({headers:{Origin:'https://foreign.test'}}))).status,403);assert.equal((await api.ebayStart(start({headers:{Authorization:''}}))).status,401);assert.equal(calls.length,0);const response=await api.ebayStart(start());assert.equal(response.status,200);const cookie=response.headers.get('Set-Cookie');assert.match(cookie,/^__Secure-resale_ebay_oauth=[A-Za-z0-9_-]{43};/);assert.match(cookie,/Secure; HttpOnly; SameSite=Lax/);assert.match(cookie,/Path=\/api\/integrations\/ebay\/callback/);assert.equal(calls[0].options.headers.Authorization,'Bearer synthetic-member');assert.equal(calls[0].input.browser_binding.length,43);env.VERCEL_ENV='preview';assert.equal((await api.ebayStart(start())).status,403);assert.equal(calls.length,1);});
test('callback requires exact state and cookie, clears query with fixed redirect, never returns OAuth material',async()=>{const {api,calls}=setup(),binding='a'.repeat(43),state='b'.repeat(43);const callback=(query,cookie)=>new Request(`${origin}/api/integrations/ebay/callback?${query}`,{headers:cookie?{Cookie:cookie}:{}});const cookie=`__Secure-resale_ebay_oauth=${binding}`;let response=await api.ebayCallback(callback(`state=${state}&code=sensitive-code`,cookie));assert.equal(response.status,303);assert.equal(response.headers.get('Location'),`${origin}/integrations/ebay?result=connected`);assert.match(response.headers.get('Set-Cookie'),/Max-Age=0/);assert.equal(calls[0].input.browser_binding,binding);assert.equal(calls[0].input.code,'sensitive-code');assert.equal(calls[0].options.headers.Authorization,undefined);assert.equal(await response.text(),'');response=await api.ebayCallback(callback(`state=${state}&code=sensitive-code`,null));assert.match(response.headers.get('Location'),/result=failed$/);await api.ebayCallback(callback(`state=${state}&state=${state}&code=code`,cookie));await api.ebayCallback(callback(`state=${state}&code=code`,`${cookie}; ${cookie}`));assert.equal(calls.length,1);});
