import {baseline,migrate} from './helpers.mjs';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
const db=await baseline();try{
 await migrate(db);const actor=randomUUID(),other=randomUUID(),account=randomUUID(),listing=randomUUID();
 await db.query('insert into auth.users values($1),($2)',[actor,other]);await db.query("insert into private.memberships(user_id,area) values($1,'resale'),($2,'resale')",[actor,other]);
 await db.query("insert into public.resale_accounts(id,marketplace,account_alias,external_account_id,username) values($1,'poshmark','synthetic','account1','synthetic_seller')",[account]);
 await db.query("insert into public.resale_listings(id,account_id,external_listing_id) values($1,$2,'listing1')",[listing,account]);
 const role=async(r,u='')=>{await db.exec(`reset role;set role ${r}`);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[u]);};const deny=(f,code)=>assert.rejects(f,e=>!code||e.code===code);
 const id=randomUUID(),payload={account_id:account,action:'update',listing_id:listing,inventory_id:null,expected_observation_id:null,expected_item_version:null,trigger:{kind:'member_request',id},requested:{scope:'poshmark_private_listing_reference',external_listing_id:'listing1'}};
 const request=(req=id,p=payload)=>db.query('select public.resale_request_listing_reference($1,$2) id',[req,p]);
 await role('authenticated',actor);const op=(await request()).rows[0].id;assert.equal((await request()).rows[0].id,op);
 await deny(()=>request(id,{...payload,requested:{...payload.requested,note:'arbitrary'}}),'22023');
 await role('authenticated',other);await deny(()=>request(),'22023');await deny(()=>db.query('select public.resale_claim_listing_reference($1,false)',[op]),'42501');
 await role('authenticated',actor);const newId=randomUUID();await deny(()=>request(newId,{...payload,trigger:{kind:'member_request',id:newId}}),'23505');
 await role('service_role');const claim=async verify=>(await db.query('select public.resale_claim_listing_reference($1,$2) value',[op,verify])).rows[0].value;
 await deny(()=>claim(null),'22023');
 const lease=await claim(false);assert.equal(lease.target.inventory_id,null);await deny(()=>claim(false),'55000');
 const protectedFields={title:'Synthetic shirt',description:'Synthetic description',photos:['photo1','photo2'],category:'Women / Tops',quantity_mode:'Single Item',size:'L',condition:'Good',brand:'Synthetic',colors:['Red'],style_tags:[],price:'22',smart_sell:'OFF',discounted_shipping:'OFF',availability:'For Sale',sku:'original-sku',cost_price:'',currency:'USD',original_price:{present:false,value:null},quantity_value:{present:false,value:null},variant_controls:[]};
 const facts=(note)=>({v:1,observed_at:new Date().toISOString(),external_listing_id:'listing1',account_handle:'synthetic_seller',external_account_id:'account1',editor_url:'https://poshmark.com/edit-listing/listing1',owner_controls_verified:true,other_info:note,protected_fields:protectedFields});
 const before=facts('Keep my old note');const preflight=(f=before,l=lease)=>db.query('select public.resale_preflight_listing_reference($1,$2,$3) value',[op,l.lease_token,f]);
 await deny(()=>preflight({...before,account_handle:'wrong'}),'22023');
 const prepared=(await preflight()).rows[0].value;assert.equal(prepared.expected_note,`Keep my old note\nResale tracker listing: ${listing}`);assert.equal(prepared.write_allowed,true);assert.deepEqual((await preflight()).rows[0].value,prepared);
 await deny(()=>preflight({...before,other_info:'changed'}),'40001');
 await deny(()=>db.query('select public.resale_pause_listing_reference($1,$2,null)',[op,lease.lease_token]),'22023');
 await db.query('select public.resale_pause_listing_reference($1,$2,$3)',[op,lease.lease_token,'save_outcome_unknown']);await deny(()=>claim(false),'55000');
 const resumed=await claim(true);assert.equal(resumed.verify_only,true);assert.equal(resumed.prior_expected_note,prepared.expected_note);
 await deny(()=>preflight(facts('No marker'),resumed),'40001');const recovered=facts(prepared.expected_note);assert.equal((await preflight(recovered,resumed)).rows[0].value.write_allowed,false);
 const finish=(f,l=resumed)=>db.query('select public.resale_finish_listing_reference($1,$2,$3) id',[op,l.lease_token,f]);
 await deny(()=>finish({...recovered,protected_fields:{...protectedFields,price:'20'}}),'40001');
 for(const change of [{original_price:{present:true,value:'50'}},{quantity_value:{present:true,value:'2'}},{variant_controls:[{size:'L',quantity:2}]}])await deny(()=>finish({...facts(prepared.expected_note),protected_fields:{...protectedFields,...change}}),'40001');
 const after=facts(prepared.expected_note);const verified=(await finish(after)).rows[0].id;assert.equal((await finish(after)).rows[0].id,verified);
 await role('postgres');const result=(await db.query('select state,target_inventory_id,verification_id from public.resale_actions where id=$1',[op])).rows[0];assert.equal(result.state,'succeeded');assert.equal(result.target_inventory_id,null);assert.equal(result.verification_id,verified);
 await deny(()=>db.query("update public.resale_actions set action='delist' where id=$1",[op]),'40001');await deny(()=>db.query("update public.resale_actions set payload='{}' where id=$1",[op]),'40001');
 assert.equal((await db.query('select count(*) n from public.resale_source_records')).rows[0].n,3);assert.equal((await db.query('select count(*) n from private.resale_listing_reference_checks')).rows[0].n,3);
 for(const t of ['inventory','sales','resale_observations','resale_pricing_observations'])assert.equal((await db.query(`select count(*) n from public.${t}`)).rows[0].n,0);
 const savedListing=(await db.query('select inventory_id,match_status from public.resale_listings where id=$1',[listing])).rows[0];assert.equal(savedListing.inventory_id,null);assert.equal(savedListing.match_status,'unmatched');
 const ordinary=randomUUID();await db.query("insert into public.resale_actions(id,listing_id,action,idempotency_key,reason,payload) values($1,$2,'update',$1::uuid::text,'synthetic','{}')",[ordinary,listing]);
 await deny(()=>db.query("update public.resale_actions set state='succeeded',verification_id=$2 where id=$1",[ordinary,verified]),'23514');
 // A browser failure before preflight can be retired after fresh readback, never blindly rewritten.
 const recoveryId=randomUUID(),recoveryPayload={...payload,trigger:{kind:'member_request',id:recoveryId}};
 await role('authenticated',actor);const recovery=(await request(recoveryId,recoveryPayload)).rows[0].id;
 await role('service_role');const claimRecovery=async()=>(await db.query('select public.resale_claim_listing_reference($1,true) value',[recovery])).rows[0].value;
 const first=(await db.query('select public.resale_claim_listing_reference($1,false) value',[recovery])).rows[0].value;
 await db.query('select public.resale_pause_listing_reference($1,$2,$3)',[recovery,first.lease_token,'browser_unavailable']);
 const readback=await claimRecovery(),unchanged=facts('Preserve this new seller note');
 const retire=(f=unchanged,stopped=true)=>db.query('select public.resale_retire_unapplied_listing_reference($1,$2,$3,$4,$5) id',[recovery,readback.lease_token,first.attempt_id,stopped,f]);
 await deny(()=>retire(unchanged,false),'22023');await deny(()=>retire(unchanged,null),'22023');
 const retired=(await retire()).rows[0].id;await deny(()=>db.query('select public.resale_preflight_listing_reference($1,$2,$3)',[recovery,readback.lease_token,unchanged]),'55000');assert.equal((await retire()).rows[0].id,retired);await deny(()=>retire({...unchanged,other_info:'changed'}),'40001');
 await role('postgres');assert.equal((await db.query('select state from public.resale_actions where id=$1',[recovery])).rows[0].state,'cancelled');
 // A preflight that authorized a write requires old-lease expiry and unchanged original controls before retirement.
 const waitId=randomUUID();await role('authenticated',actor);const waiting=(await request(waitId,{...payload,trigger:{kind:'member_request',id:waitId}})).rows[0].id;
 await role('service_role');const writeLease=(await db.query('select public.resale_claim_listing_reference($1,false) value',[waiting])).rows[0].value;
 await db.query('select public.resale_preflight_listing_reference($1,$2,$3)',[waiting,writeLease.lease_token,facts('old')]);
 await db.query('select public.resale_pause_listing_reference($1,$2,$3)',[waiting,writeLease.lease_token,'save_outcome_unknown']);
 let verifyLease=(await db.query('select public.resale_claim_listing_reference($1,true) value',[waiting])).rows[0].value;
 const notApplied=(f)=>db.query('select public.resale_retire_unapplied_listing_reference($1,$2,$3,true,$4)',[waiting,verifyLease.lease_token,writeLease.attempt_id,f]);
 await db.query('select public.resale_pause_listing_reference($1,$2,$3)',[waiting,verifyLease.lease_token,'browser_unavailable']);
 const priorReader=verifyLease;verifyLease=(await db.query('select public.resale_claim_listing_reference($1,true) value',[waiting])).rows[0].value;
 await deny(()=>db.query('select public.resale_retire_unapplied_listing_reference($1,$2,$3,true,$4)',[waiting,verifyLease.lease_token,priorReader.attempt_id,facts('old')]),'22023');
 await deny(()=>notApplied(facts('new seller note')),'40001');await deny(()=>notApplied(facts('old')),'55000');
 await role('postgres');await db.query("update public.resale_action_attempts set evidence=evidence||jsonb_build_object('lease_expires_at',clock_timestamp()-interval '31 seconds') where id=$1",[writeLease.attempt_id]);
 await role('service_role');await notApplied(facts('old'));
 await role('postgres');
 await db.query("delete from private.memberships where user_id=$1 and area='resale'",[actor]);await role('service_role');await deny(()=>claim(true),'42501');await role('authenticated',actor);await deny(()=>request(),'42501');
 console.log('PASS listing-only exact request/retry, ordinary-member proof denial, single open request, protected note append, uncertain readback recovery, immutable scope, membership and zero stock/sale changes');
}catch(e){console.error(e.message,e.code||'');process.exitCode=1;}finally{await db.close();}
