import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../workers/resale-media/worker.mjs';
import {photoMac,safePhotoUrl} from '../workers/resale-media/listing-photos.mjs';
const id=n=>`${String(n).padStart(8,'0')}-1111-4111-8111-111111111111`,hex=b=>Buffer.from(b).toString('hex');
const png=Uint8Array.from([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,1,0,0,0,1]);
function setup(t){
 const objects=new Map(),calls=[],receipts=[];
 const ref={id:id(1),source_record_id:id(2),account_id:id(3),listing_id:id(4),external_account_id:'account1',external_listing_id:'a'.repeat(24),source_url:`https://di2ponv0v5otw.cloudfront.net/posts/2026/09/05/${'a'.repeat(24)}/l_${'b'.repeat(24)}.png`,kind:'marketplace_copy',state:'saving'};
 const job={request_id:id(5),member_id:id(6),nonce:id(7),lease_token:id(8),expires_at:Date.now()/1000+600,job_state:'leased',ref};
 const flags={deny:false,sourceStatus:200,sourceBytes:png,sourceMime:'image/png',sourceCalls:0,failFinalize:false};
 const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public',MEDIA_RECEIPT_KEY:'ab'.repeat(32),ALLOWED_ORIGINS:'https://app.example',RESALE_ORIGINALS:{
 async head(k){return objects.get(k)||null},async get(k){const o=objects.get(k);return o?{...o,body:o.bytes,text:async()=>new TextDecoder().decode(o.bytes)}:null},
 async put(k,bytes,opts){calls.push(k);assert.equal(opts.onlyIf.get('If-None-Match'),'*');assert.equal(hex(opts.sha256),hex(await crypto.subtle.digest('SHA-256',bytes)));if(objects.has(k))return null;const o={bytes:new Uint8Array(bytes),size:bytes.length,checksums:{sha256:opts.sha256},httpMetadata:opts.httpMetadata,customMetadata:opts.customMetadata};objects.set(k,o);return o;}
 }};
 const original=globalThis.fetch;t.after(()=>{globalThis.fetch=original});
 globalThis.fetch=async(url,options)=>{
 assert.equal(options.redirect,'manual');
 if(url===ref.source_url){flags.sourceCalls++;assert.equal(options.credentials,'omit');assert.equal(options.headers.Authorization,undefined);return new Response(flags.sourceBytes,{status:flags.sourceStatus,headers:{'Content-Type':flags.sourceMime,'Content-Length':String(flags.sourceBytes.length)}})}
 if(url.endsWith('/auth/v1/user'))return Response.json({id:job.member_id});
 if(url.endsWith('/rpc/resale_access'))return Response.json(!flags.deny);
 if(url.endsWith('/rpc/resale_prepare_listing_photo'))return Response.json(job);
 if(url.endsWith('/rpc/resale_claim_listing_photo_dispatch'))return Response.json(job);
 if(url.endsWith('/rpc/resale_finish_listing_photo')){const b=JSON.parse(options.body);assert.equal(options.headers.Authorization,undefined);assert.equal(b.p_signature,await photoMac(env.MEDIA_RECEIPT_KEY,'receipt',b.p_receipt));const r=JSON.parse(b.p_receipt);receipts.push(r);if(flags.failFinalize)throw Error('uncertain transport');if(r.kind==='marketplace_copy_error'){ref.state='saving';ref.last_error=r.error;return Response.json(ref)}if(job.job_state!=='leased')return new Response('{}',{status:409});ref.state='ready';ref.object_sha256=r.sha256;job.object=r;job.job_state='ready';return Response.json(ref)}
 if(url.includes('/resale_listing_photo_refs?'))return Response.json([ref]);
 if(url.includes('/resale_marketplace_photo_objects?'))return Response.json([job.object]);
 throw Error('Unexpected request '+url);
 };
 const request=(method='POST',body={request_id:job.request_id},auth=true)=>new Request(`https://media.example/v1/listing-photos/${ref.id}`,{method,headers:{Origin:'https://app.example',...(auth?{Authorization:'Bearer valid'}:{}),'Content-Type':'application/json'},...(method==='POST'?{body:JSON.stringify(body)}:{})});
 return {env,ref,job,flags,calls,objects,receipts,request};
}
test('preserves bytes in private content-addressed object; exact retry, authorized preview, no original relabel',async t=>{const s=setup(t);const r=await worker.fetch(s.request(),s.env);assert.equal(r.status,200);assert.equal(s.ref.state,'ready');assert.equal(s.receipts[0].kind,'marketplace_copy');const key=s.job.object.object_key;assert.deepEqual(s.objects.get(key).bytes,png);assert.equal((await worker.fetch(s.request(),s.env)).status,200);assert.equal(s.flags.sourceCalls,1);assert.equal(s.calls.length,2);const get=await worker.fetch(s.request('GET'),s.env);assert.equal(get.status,200);assert.deepEqual(new Uint8Array(await get.arrayBuffer()),png);assert.equal(get.headers.get('Cache-Control'),'private, no-store');s.flags.deny=true;assert.equal((await worker.fetch(s.request('GET'),s.env)).status,403)});
test('uncertain finalization resumes immutable capture without refetching changed remote bytes',async t=>{const s=setup(t);s.flags.failFinalize=true;assert.equal((await worker.fetch(s.request(),s.env)).status,503);assert.equal(s.job.job_state,'leased');assert.equal(s.receipts.length,1);s.flags.sourceBytes=png.slice();s.flags.sourceBytes[23]=9;s.flags.failFinalize=false;assert.equal((await worker.fetch(s.request(),s.env)).status,200);assert.equal(s.flags.sourceCalls,1);assert.deepEqual(s.objects.get(s.job.object.object_key).bytes,png)});
test('unsafe URLs, caller URLs, redirects and active MIME fail without accepting photos',async t=>{const s=setup(t);assert.equal((await worker.fetch(s.request('POST',{request_id:s.job.request_id,url:'https://evil.example'}),s.env)).status,400);s.ref.source_url+='?url=bad';assert.equal((await worker.fetch(s.request(),s.env)).status,409);assert.equal(s.flags.sourceCalls,0);s.ref.source_url=s.ref.source_url.split('?')[0];s.flags.sourceStatus=302;assert.equal((await worker.fetch(s.request(),s.env)).status,503);assert.equal(s.receipts[0].error,'source_rejected');assert.equal(s.objects.size,0)});
test('signatures are separated from original receipts and dispatch; unbound public calls cannot capture',async t=>{const s=setup(t);assert.equal((await worker.fetch(s.request('POST',{},false),s.env)).status,401);const ticket='{}';const wrong=await photoMac(s.env.MEDIA_RECEIPT_KEY,'receipt',ticket);const req=new Request('https://media.example/v1/listing-photo-dispatch',{method:'POST',body:JSON.stringify({ticket,signature:wrong})});assert.equal((await worker.fetch(req,s.env)).status,401);assert.equal(s.flags.sourceCalls,0);assert.notEqual(wrong,await photoMac(s.env.MEDIA_RECEIPT_KEY,'dispatch',ticket));assert.equal(safePhotoUrl({...s.ref,source_url:s.ref.source_url.replace('https://','http://')}),false)});
test('captured manifest corruption cannot redirect a resumed fetch or finalize a different binding',async t=>{const s=setup(t);s.flags.failFinalize=true;await worker.fetch(s.request(),s.env);const k=s.calls[0],o=s.objects.get(k);o.bytes=new TextEncoder().encode('{}');o.size=o.bytes.length;s.flags.failFinalize=false;assert.equal((await worker.fetch(s.request(),s.env)).status,503);assert.equal(s.flags.sourceCalls,1);assert.equal(s.ref.state,'saving')});
test('R2 checksum mismatch is never presented as saved',async t=>{const s=setup(t);await worker.fetch(s.request(),s.env);s.objects.get(s.job.object.object_key).checksums.sha256=new Uint8Array(32).buffer;assert.equal((await worker.fetch(s.request('GET'),s.env)).status,409);assert.equal((await worker.fetch(s.request(),s.env)).status,409)});

test('manifest PUT committed but response lost remains leased and resumes the captured bytes',async t=>{const s=setup(t),put=s.env.RESALE_ORIGINALS.put;let lost=true;s.env.RESALE_ORIGINALS.put=async(...args)=>{const result=await put(...args);if(lost&&args[0].includes('/captures/')){lost=false;throw Error('response lost');}return result;};assert.equal((await worker.fetch(s.request(),s.env)).status,503);assert.equal(s.job.job_state,'leased');assert.equal(s.receipts.length,0);assert.equal((await worker.fetch(s.request(),s.env)).status,200);assert.deepEqual(s.objects.get(s.job.object.object_key).bytes,png)});
test('same-request concurrent changed bytes cannot let loser invalidate winner',async t=>{const s=setup(t),baseFetch=globalThis.fetch;let reads=0,release;const gate=new Promise(r=>{release=r});globalThis.fetch=async(url,opts)=>{if(url===s.ref.source_url){const n=++reads;if(n===1)await gate;else release();const bytes=png.slice();if(n===2)bytes[23]=2;return new Response(bytes,{headers:{'Content-Type':'image/png','Content-Length':String(bytes.length)}});}return baseFetch(url,opts);};const responses=await Promise.all([worker.fetch(s.request(),s.env),worker.fetch(s.request(),s.env)]);assert.ok(responses.some(r=>r.status===200));assert.equal(s.job.job_state,'ready');assert.equal(s.receipts.some(r=>r.kind==='marketplace_copy_error'),false);assert.equal(s.objects.size,2)});

test('concurrent failed source read cannot invalidate a valid same-lease capture',async t=>{const s=setup(t),baseFetch=globalThis.fetch;let count=0;globalThis.fetch=async(url,opts)=>{if(url===s.ref.source_url&&++count===1)return new Response('',{status:503});return baseFetch(url,opts);};const responses=await Promise.all([worker.fetch(s.request(),s.env),worker.fetch(s.request(),s.env)]);assert.ok(responses.some(r=>r.status===200));assert.equal(s.ref.state,'ready');assert.equal(s.job.job_state,'ready');assert.equal(s.receipts.filter(r=>r.kind==='marketplace_copy').length,1)});
