import {baseline,migrate} from './helpers.mjs';import assert from 'node:assert/strict';import {randomUUID,createHmac} from 'node:crypto';
const db=await baseline(),key='ab'.repeat(32);try{
 await migrate(db);await db.exec('create schema vault;create table vault.secrets(name text,secret text);create view vault.decrypted_secrets as select name,secret as decrypted_secret from vault.secrets;');await db.query('insert into vault.secrets values($1,$2)',['resale_media_production_receipt_signing_key',key]);
 const owner=randomUUID(),other=randomUUID(),account=randomUUID(),listing=randomUUID(),snapshot=randomUUID(),source=randomUUID();
 await db.query('insert into auth.users values($1),($2)',[owner,other]);await db.query("insert into private.memberships(user_id,area) values($1,'resale'),($2,'resale')",[owner,other]);await db.query("insert into public.resale_accounts(id,marketplace,account_alias,external_account_id,username) values($1,'poshmark','synthetic','seller1','synthetic_seller')",[account]);await db.query("insert into public.resale_listings(id,account_id,external_listing_id) values($1,$2,'1234567890abcdef12345678')",[listing,account]);await db.query("insert into public.resale_snapshots(id,account_id,source,source_ref,observed_at,scope,coverage) values($1,$2,'browser','synthetic',now(),'cover only','partial')",[snapshot,account]);
 const url='https://di2ponv0v5otw.cloudfront.net/posts/2026/09/05/1234567890abcdef12345678/l_1234567890abcdef12345679.jpg';await db.query("insert into public.resale_source_records(id,snapshot_id,account_id,record_key,source_kind,raw_business,normalized,external_identifiers,source_observed_at,captured_at,record_status) values($1,$2,$3,'one','browser','{}',$4,'{\"listing_id\":\"1234567890abcdef12345678\",\"account_id\":\"seller1\"}',now(),now(),'accepted')",[source,snapshot,account,{marketplace_photos:[{position:0,role:'cover',url},{position:1,role:'gallery',url}]}]);
 const role=async(r,u='')=>{await db.exec(`reset role;set role ${r}`);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[u]);};const deny=(f,code)=>assert.rejects(f,e=>!code||e.code===code);
 const register=()=>db.query('select * from public.resale_register_listing_photos($1,$2,$3)',[owner,listing,source]);await role('authenticated',owner);await deny(register,'42501');await role('service_role');const refs=(await register()).rows;assert.equal(refs.length,2);assert.deepEqual((await register()).rows.map(r=>r.id),refs.map(r=>r.id));
 const request=randomUUID();await db.query('select public.resale_prepare_listing_photo_admin($1,$2,$3)',[owner,request,refs[0].id]);
 await role('postgres');const job=(await db.query('select * from private.resale_listing_photo_jobs where id=$1',[request])).rows[0];const ticket={v:1,kind:'marketplace_copy_dispatch',request_id:job.id,member_id:owner,ref_id:refs[0].id,source_record_id:source,account_id:account,listing_id:listing,source_url:url,nonce:job.nonce,expires_at:Math.round(new Date(job.expires_at).getTime()/1000)};
 const mac=(domain,s)=>createHmac('sha256',Buffer.from(key,'hex')).update(`resale:marketplace-copy:${domain}:v1\n${s}`).digest('hex');const text=JSON.stringify(ticket),signature=mac('dispatch',text);
 await role('anon');await deny(()=>db.query('select public.resale_claim_listing_photo_dispatch($1,$2)',[text,mac('receipt',text)]),'42501');await deny(()=>db.query('select public.resale_prepare_listing_photo_admin($1,$2,$3)',[owner,request,refs[0].id]),'42501');
 const claimed=(await db.query('select public.resale_claim_listing_photo_dispatch($1,$2) value',[text,signature])).rows[0].value;assert.equal(claimed.ref.id,refs[0].id);assert.equal((await db.query('select public.resale_claim_listing_photo_dispatch($1,$2) value',[text,signature])).rows[0].value.lease_token,claimed.lease_token);
 const receiptFor=(j,ref)=>({v:1,kind:'marketplace_copy',request_id:j.request_id,member_id:owner,ref_id:ref.id,source_record_id:source,account_id:account,listing_id:listing,external_account_id:'seller1',external_listing_id:'1234567890abcdef12345678',source_url:url,nonce:j.nonce,lease_token:j.lease_token,expires_at:Math.floor(Date.now()/1000)+600,sha256:'cd'.repeat(32),bucket:'paulette-resale-originals-prod',object_key:'resale/marketplace-copies/sha256/'+'cd'.repeat(32),byte_size:100,mime_type:'image/jpeg',fetched_at:new Date().toISOString()});
 const finish=async p=>{const receipt=JSON.stringify(p);return db.query('select to_jsonb(public.resale_finish_listing_photo($1,$2)) value',[receipt,mac('receipt',receipt)]);};
 await deny(()=>finish({...receiptFor(claimed,refs[0]),source_url:url+'?other'}),'40001');const receipt=receiptFor(claimed,refs[0]);assert.equal((await finish({...receipt,kind:'marketplace_copy_error',error:'source_unavailable'})).rows[0].value.state,'saving');assert.equal((await finish(receipt)).rows[0].value.state,'ready');assert.equal((await finish(receipt)).rows[0].value.state,'ready');
 await role('authenticated',owner);await deny(()=>db.query("update public.resale_listing_photo_refs set source_url='bad'"),'42501');const next=(await db.query('select public.resale_prepare_listing_photo($1,$2) value',[randomUUID(),refs[1].id])).rows[0].value;await finish(receiptFor(next,refs[1]));assert.equal((await db.query('select count(*) n from public.resale_marketplace_photo_objects')).rows[0].n,1);
 await role('postgres');await deny(()=>db.query("update public.resale_listing_photo_refs set role='gallery' where id=$1",[refs[0].id]),'55000');for(const t of ['inventory','sales','resale_media','resale_observations'])assert.equal((await db.query(`select count(*) n from public.${t}`)).rows[0].n,0);
 assert.equal((await db.query('select inventory_id from public.resale_listings where id=$1',[listing])).rows[0].inventory_id,null);
 await db.query("delete from private.memberships where user_id=$1 and area='resale'",[owner]);await role('anon');await deny(()=>finish(receipt),'42501');
 await role('postgres');await db.query('update vault.secrets set secret=null');await role('anon');await deny(()=>db.query('select public.resale_claim_listing_photo_dispatch($1,$2)',[text,signature]),'55000');
 console.log('PASS exact trusted photo source, member/admin isolation, HMAC domains/nonce/retry, byte dedupe, immutable provenance, revocation and zero original/physical effects');
}catch(e){console.error(e.message,e.code||'');process.exitCode=1;}finally{await db.close();}
