import assert from 'node:assert/strict'
import { baseline,migrate } from './helpers.mjs'
import { fixture,uid,hash,sign,tickKey,ingressKey,mailbox,scope,normalized,receipt,rpc,enroll,oauth,complete,claim,ingest } from './gmail-fixture.mjs'
const db=await baseline()
const deny=(fn,code='42501')=>assert.rejects(fn,e=>e.code===code)
const role=async(name,id='')=>{await db.exec(`reset role;set role ${name}`);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id])}
try {
 await migrate(db);const {owner,other,outsider,account,accountB}=await fixture(db)
 const canonical=async()=>{const result={};for(const t of ['inventory','sales','resale_order_lines','resale_listings','resale_listing_match_history']){result[t]=(await db.query(`select coalesce(jsonb_agg(to_jsonb(t) order by id),'[]'::jsonb) data from public.${t} t`)).rows[0].data}return result}
 // Probe real table names instead of assuming an absent audit relation.
 const available=(await db.query("select to_regclass('public.resale_listing_match_history') name")).rows[0].name
 if(!available)throw Error('matching audit table name changed')
 const before=await canonical()
 await role('authenticated',owner);const request=uid(),feed=await enroll(db,account,request)
 assert.equal(await enroll(db,account,request),feed)
 await deny(()=>enroll(db,accountB,request),'22023')
 await deny(()=>rpc(db,'resale_enroll_gmail_feed',[uid(),{mailbox_email:'wrong@example.test',account_id:account,parser_version:'vinted-gmail-v1'}]),'22023')
 await deny(()=>db.query("update public.resale_gmail_feeds set status='active'"))
 for(const query of ['select * from private.resale_gmail_runtime','select private.gmail_client_secret()','select private.gmail_ingress_key()','select private.gmail_check_signature(\'tick\',\'{}\',\'abc\')'])await deny(()=>db.query(query))
 await deny(()=>oauth(db,owner,feed))
 await role('authenticated',other);assert.equal((await db.query('select * from public.resale_gmail_feeds')).rows.length,0);await deny(()=>enroll(db,account,request),'22023');await deny(()=>rpc(db,'resale_pause_gmail_feed',[feed]))
 await role('authenticated',outsider);await deny(()=>enroll(db,account))
 await role('anon');await deny(()=>db.query('select * from public.resale_gmail_feeds'));await deny(()=>enroll(db,account))
 await role('service_role');await deny(()=>db.query('select * from private.resale_gmail_runtime'));await deny(()=>db.query('select private.gmail_refresh_token()'))
 await deny(()=>oauth(db,other,feed))
 let s=await oauth(db,owner,feed,{consume:false})
 await deny(()=>rpc(db,'resale_gmail_oauth_consume',[s.state,hash('wrong')]),'22023')
 const consumed=await rpc(db,'resale_gmail_oauth_consume',[s.state,s.binding]);assert.equal(consumed.code_verifier,'a'.repeat(43));assert.equal(consumed.expected_mailbox,mailbox)
 await deny(()=>rpc(db,'resale_gmail_oauth_consume',[s.state,s.binding]),'22023')
 await deny(()=>complete(db,s,null),'22023')
 await deny(()=>rpc(db,'resale_gmail_oauth_complete',[s.state_id,'wrong@example.test',scope,'synthetic-refresh-token']),'22023')
 await deny(()=>rpc(db,'resale_gmail_oauth_complete',[s.state_id,mailbox,[...scope,'openid'],'synthetic-refresh-token']),'22023')
 assert.equal((await complete(db,s)).status,'paused');assert.equal((await complete(db,s)).status,'paused');await deny(()=>complete(db,s,'changed-synthetic-token'),'22023')
 await role('postgres');assert.equal((await db.query('select code_verifier from private.resale_gmail_oauth_states where id=$1',[s.state_id])).rows[0].code_verifier,null)
 await db.query("update private.resale_gmail_config set publishing_status='production'")
 await role('service_role');s=await oauth(db,owner,feed);assert.equal((await complete(db,s,null)).status,'active')
 await role('postgres');await db.query("update private.resale_gmail_config set client_id='synthetic-client-two'")
 await role('service_role');s=await oauth(db,owner,feed);await deny(()=>complete(db,s,null),'22023');assert.equal((await complete(db,s,'second-client-synthetic-token')).status,'active')
 console.log('PASS owner-only enrollment, single-use bound OAuth, exact scope/mailbox, Testing pause and refresh-token/client association')
 await role('postgres');await db.query("update vault.secrets set secret=null where name like '%tick_signing_key'")
 await role('service_role');await deny(()=>claim(db),'55000')
 await role('postgres');await db.query("update vault.secrets set secret=$1 where name like '%tick_signing_key'",[tickKey]);await db.query("update vault.secrets set secret=null where name like '%ingress_signing_key'")
 await role('service_role');await deny(()=>claim(db),'55000')
 await role('postgres');await db.query("update vault.secrets set secret=$1 where name like '%ingress_signing_key'",[ingressKey])
 await role('service_role');await deny(()=>claim(db,{expires_at:Math.floor(Date.now()/1000)-5}),'22023');await deny(()=>claim(db,{expires_at:Math.floor(Date.now()/1000)+1000}),'22023')
 await deny(()=>rpc(db,'resale_gmail_verify_tick_and_claim',['{}','0'.repeat(64)]))
 const first=await claim(db),lease=first.result.lease_token;assert.equal(first.result.account_handle,'synthetic_seller');assert.equal(first.result.cursor,null)
 assert.equal(await rpc(db,'resale_gmail_verify_tick_and_claim',[first.text,sign('tick',first.text)]),null);assert.equal((await claim(db)).result,null)
 const changedTick=JSON.stringify({...JSON.parse(first.text),expires_at:Math.floor(Date.now()/1000)+200});await deny(()=>rpc(db,'resale_gmail_verify_tick_and_claim',[changedTick,sign('tick',changedTick)]),'22023')
 const cursor={window_start_ms:Date.now()-86400000,window_end_ms:Date.now()-60000,page_token:null,window_complete:false}
 await deny(()=>rpc(db,'resale_gmail_checkpoint_run',[feed,lease,{...cursor,pending_message_ids:['invalid!']}]),'22023')
 await deny(()=>rpc(db,'resale_gmail_checkpoint_run',[feed,lease,{...cursor,pending_message_ids:Array(26).fill('abc')}]),'22023')
 await rpc(db,'resale_gmail_checkpoint_run',[feed,lease,{...cursor,pending_message_ids:['abc','def'],next_page_token:'next'}])
 await rpc(db,'resale_gmail_checkpoint_run',[feed,lease,cursor])
 await deny(()=>rpc(db,'resale_gmail_checkpoint_run',[feed,lease,{...cursor,window_start_ms:cursor.window_start_ms+1000}]),'22023')
 await deny(()=>rpc(db,'resale_gmail_finish_run',[feed,lease,'complete',cursor,null]),'22023')
 await deny(()=>ingest(db,receipt(feed,lease,account,{received_at:cursor.window_start_ms-1})),'22023')
 const one=receipt(feed,lease,account),out=await ingest(db,one);assert.equal(out.duplicate,false)
 assert.deepEqual(await ingest(db,one),{...out,duplicate:true})
 assert.deepEqual(await ingest(db,{...one,nonce:uid(),captured_at:Date.now()}),{...out,duplicate:true})
 await deny(()=>ingest(db,{...one,nonce:uid(),source_sha256:hash('changed')}),'22023')
 await deny(()=>ingest(db,{...one,nonce:uid(),account_id:accountB}),'22023')
 await deny(()=>ingest(db,{...one,nonce:uid(),normalized:{...one.normalized,account_handle:'wrong'}}),'22023')
 await deny(()=>ingest(db,{...one,nonce:uid(),normalized:{...one.normalized,order_id:'fabricated'}}),'22023')
 for(const field of ['source_sha256','kind','parser_version','expires_at','received_at','account_id'])await deny(()=>ingest(db,{...one,nonce:uid(),[field]:null}),'22023')
 await deny(()=>rpc(db,'resale_ingest_gmail_message',[JSON.stringify(one),'0'.repeat(64)]))
 await role('authenticated',owner);await deny(()=>ingest(db,one));await role('service_role')
 const quarantined=receipt(feed,lease,account,{message_id:'quarantine',kind:'unknown',normalized:{...normalized(),account_handle:null,authentication_pass:false,parser_status:'quarantined',quarantine_reason:'unrecognized_template'}})
 await ingest(db,quarantined)
 await role('postgres');const rows=(await db.query('select * from public.resale_source_records where id=$1',[out.source_record_id])).rows
 assert.equal(rows[0].event_time,null);assert.equal(rows[0].event_precision,'unknown');assert.equal(rows[0].external_identifiers.order_id,null)
 const task=(await db.query('select * from public.resale_actions where id=$1',[out.operation_id])).rows[0]
 assert.equal(task.state,'blocked');assert.equal(task.action,'reconcile_sale');assert.equal(task.listing_id,null);assert.equal(task.target_inventory_id,null)
 assert.equal((await db.query('select actor_id from private.resale_operation_requests where operation_id=$1',[out.operation_id])).rows[0].actor_id,owner)
 const legacySnap=uid(),legacySource=uid();await db.query("insert into public.resale_snapshots(id,account_id,source,source_ref,observed_at,scope,coverage) values($1,$2,'manual','synthetic:legacy',now(),'synthetic legacy email','partial')",[legacySnap,account])
 await db.query("insert into public.resale_source_records(id,snapshot_id,account_id,record_key,source_kind,external_identifiers,event_precision,captured_at,raw_business,record_status) values($1,$2,$3,'legacy','email','{\"gmail_message_id\":\"legacymsg\"}','unknown',now(),'{\"retained\":true}','accepted')",[legacySource,legacySnap,account])
 const old=(await db.query('select to_jsonb(s) value from public.resale_source_records s where id=$1',[legacySource])).rows[0].value
 await role('service_role');const legacy=await ingest(db,receipt(feed,lease,account,{message_id:'legacymsg',kind:'shipping_notification',normalized:{...normalized(),transaction_id:'123456'}}))
 assert.equal(legacy.legacy_source_reused,true);assert.equal(legacy.source_record_id,legacySource)
 await role('postgres');assert.deepEqual((await db.query('select to_jsonb(s) value from public.resale_source_records s where id=$1',[legacySource])).rows[0].value,old)
 assert.equal((await db.query('select count(*) n from public.resale_review_cases')).rows[0].n,2)
 assert.deepEqual(await canonical(),before)
 console.log('PASS null keys fail closed, signed nonce replay, exact message dedupe, legacy immutable reuse and evidence-only blocked tasks')
 await role('service_role');await rpc(db,'resale_gmail_finish_run',[feed,lease,'partial',{...cursor,page_token:'next'},null])
 await role('postgres');assert.equal((await db.query('select last_success_at from public.resale_gmail_feeds')).rows[0].last_success_at,null);await db.query('update private.resale_gmail_runtime set not_before=null')
 await role('service_role');const run2=(await claim(db)).result;assert.equal(run2.cursor.window_complete,false)
 await rpc(db,'resale_gmail_finish_run',[feed,run2.lease_token,'complete',{...cursor,window_complete:true},null])
 await role('postgres');assert((await db.query('select last_success_at from public.resale_gmail_feeds')).rows[0].last_success_at);await db.query('update private.resale_gmail_runtime set not_before=null')
 await role('service_role');const run3=(await claim(db)).result
 await deny(()=>rpc(db,'resale_gmail_checkpoint_run',[feed,run3.lease_token,{...cursor,window_start_ms:cursor.window_end_ms+1,window_end_ms:Date.now()-1000}]),'22023')
 await role('authenticated',owner);await rpc(db,'resale_pause_gmail_feed',[feed]);await role('service_role');await deny(()=>ingest(db,receipt(feed,run3.lease_token,account,{message_id:'afterpause'})),'22023')
 s=await oauth(db,owner,feed,{consume:false});await role('postgres');await db.query("delete from private.memberships where user_id=$1 and area='resale'",[owner]);await role('service_role');await deny(()=>rpc(db,'resale_gmail_oauth_consume',[s.state,s.binding]));await role('authenticated',owner);assert.equal((await db.query('select * from public.resale_gmail_feeds')).rows.length,0)
 console.log('PASS fixed-window checkpoints, partial/complete watermarks, pause fencing and live membership revocation')
}catch(e){console.error({message:e.message,code:e.code,where:e.where,stack:e.code && e.code!=="ERR_ASSERTION"?undefined:e.stack});process.exitCode=1}finally{await db.close()}
