import assert from 'node:assert/strict';
import {baseline,migrate} from './helpers.mjs';
import {fixture,uid,hash} from './gmail-fixture.mjs';
async function rpc(db,name,args){return (await db.query(`select to_jsonb(public.${name}(${args.map((_,i)=>`$${i+1}`).join(',')})) value`,args.map(v=>v&&typeof v==='object'?JSON.stringify(v):v))).rows[0].value}
const db=await baseline(),role=async(r,id='')=>{await db.exec(`reset role;set role ${r}`);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id])};
const deny=(f,code)=>assert.rejects(f,e=>e.code===code);
try{
 await migrate(db);const {owner,other}=await fixture(db),account=uid();
 await db.query("insert into public.resale_accounts(id,marketplace,account_alias,username) values($1,'ebay','synthetic','paulbr-89')",[account]);
 await db.query("insert into private.resale_ebay_config(client_id,runame,trading_version,callback,deletion_endpoint,activation_ready,deletion_receipts_ready,deletion_coverage_review) values('synthetic','synthetic-runame','1423','https://resell-tracker-beta.vercel.app/api/integrations/ebay/callback','https://resell-tracker-beta.vercel.app/api/integrations/ebay/deletion',true,true,'synthetic-only')");
 await db.query("insert into vault.secrets(name,secret) values('resale_ebay_production_oauth_client_secret','synthetic')");
 await role('authenticated',owner);await rpc(db,'resale_ebay_enroll',[account]);await role('service_role');
 async function authorize(){const state=hash(uid()),browser=hash(uid());await rpc(db,'resale_ebay_oauth_start',[owner,account,state,browser]);const c=await rpc(db,'resale_ebay_oauth_consume',[state,browser]);await rpc(db,'resale_ebay_oauth_complete',[c.state_id,'paulbr-89',hash('seller'),'synthetic-token',86400]);}
 await authorize();
 const oldListing=uid(),snap=uid(),oldObs=uid();await role('postgres');
 await db.query("insert into public.resale_listings(id,account_id,external_listing_id,title,desired_fields,draft_context,asking_price,match_status) values($1,$2,'123456789012','Preserved title','{\"title\":\"Paulette draft\"}','{}',30,'proposed')",[oldListing,account]);
 await db.query("insert into public.resale_snapshots(id,account_id,source,source_ref,observed_at,scope,coverage) values($1,$2,'browser','synthetic-legacy',clock_timestamp()-interval '1 day','one','partial')",[snap,account]);
 await db.query("insert into public.resale_observations(id,snapshot_id,account_id,listing_id,observed_at,status) values($1,$2,$3,$4,clock_timestamp()-interval '1 day','reserved')",[oldObs,snap,account,oldListing]);
 const preserve=(await db.query('select title,desired_fields,draft_context,draft_version,asking_price,match_status,inventory_id from public.resale_listings where id=$1',[oldListing])).rows[0];
 const stock=(await db.query('select (select count(*) from public.inventory) inventory,(select count(*) from public.sales) sales')).rows[0];
 await role('service_role');const runId=uid(),run=await rpc(db,'resale_ebay_start_listing_run',[owner,account,runId]);assert.equal((await rpc(db,'resale_ebay_start_listing_run',[owner,account,runId])).next_request_id,run.next_request_id);
 await deny(()=>rpc(db,'resale_ebay_start_listing_run',[other,account,runId]),'42501');
 const record=id=>({listing_id:id,title:'API title',observed_status:'active',quantity_available:1,quantity_total:1,current_price:{value:'22.00',currency:'USD'},sku:null,listing_type:'FixedPriceItem',has_variations:false});
 async function page(id,records,pages,entries){const claim=await rpc(db,'resale_ebay_claim_listing_run',[owner,id]);const request=claim.request;const lease=await rpc(db,'resale_ebay_claim_read',[owner,account,request.request_id,'listings',request.page,null,null]);const result={records,page:request.page,total_pages:pages,total_entries:entries,has_more:request.page<pages,coverage:'active_only',source_sha256:hash(JSON.stringify(records))};await rpc(db,'resale_ebay_finish_read',[owner,request.request_id,lease.lease,result,null]);return request;}
 const one=await page(runId,[record('123456789012')],2,2);
 // An interrupted checkpoint resumes the completed receipt, not a second provider request.
 const resumed=await rpc(db,'resale_ebay_claim_listing_run',[owner,runId]);assert.equal(resumed.request.request_id,one.request_id);assert.equal((await rpc(db,'resale_ebay_claim_read',[owner,account,one.request_id,'listings',1,null,null])).cached,true);
 let progress=await rpc(db,'resale_ebay_checkpoint_listing_run',[owner,runId,one.request_id]);assert.equal(progress.status,'running');assert.equal(progress.records_read,1);assert.equal((await rpc(db,'resale_ebay_checkpoint_listing_run',[owner,runId,one.request_id])).next_request_id,progress.next_request_id);
 const two=await page(runId,[record('123456789013')],2,2);progress=await rpc(db,'resale_ebay_checkpoint_listing_run',[owner,runId,two.request_id]);assert.equal(progress.status,'complete');assert.equal(progress.records_read,2);assert.match(progress.coverage_note,/not an atomic/);
 await role('postgres');assert.deepEqual((await db.query('select title,desired_fields,draft_context,draft_version,asking_price,match_status,inventory_id from public.resale_listings where id=$1',[oldListing])).rows[0],preserve);assert.equal((await db.query('select observed_status from public.resale_listings where id=$1',[oldListing])).rows[0].observed_status,'active');assert.equal((await db.query("select count(*) n from public.resale_source_records where source_kind='official_api'")).rows[0].n,2);assert.deepEqual((await db.query('select (select count(*) from public.inventory) inventory,(select count(*) from public.sales) sales')).rows[0],stock);
 const source=(await db.query('select source_id from private.resale_ebay_listing_ingests limit 1')).rows[0].source_id;await deny(()=>db.query('delete from public.resale_source_records where id=$1',[source]),'55000');
 await role('authenticated',other);assert.equal((await db.query('select * from public.resale_ebay_listing_runs')).rows.length,0);await deny(()=>rpc(db,'resale_ebay_cancel_listing_run',[runId]),'42501');await role('anon');await deny(()=>db.query('select * from public.resale_ebay_listing_runs'),'42501');await role('service_role');
 // Count shifts and repeated IDs stop the run; missing listings never receive ended/sold observations.
 for(const mode of ['duplicate','count_shift','gap']){const id=uid();await rpc(db,'resale_ebay_start_listing_run',[owner,account,id]);const p=await page(id,[record('123456789014')],2,2);await rpc(db,'resale_ebay_checkpoint_listing_run',[owner,id,p.request_id]);const p2=await page(id,mode==='gap'?[]:[record(mode==='duplicate'?'123456789014':'123456789015')],2,mode==='count_shift'?3:2);const end=await rpc(db,'resale_ebay_checkpoint_listing_run',[owner,id,p2.request_id]);assert.equal(end.status,'needs_review');assert.equal(end.last_error,{duplicate:'duplicate_listing_across_pages',count_shift:'provider_totals_changed',gap:'provider_count_gap'}[mode]);}
 // Real reauthorization rotates generation; an old run cannot ingest the next page.
 const stale=uid();await rpc(db,'resale_ebay_start_listing_run',[owner,account,stale]);await authorize();assert.equal((await rpc(db,'resale_ebay_claim_listing_run',[owner,stale])).run.status,'needs_review');
 // Retained equal-time conflict must stay unknown after removing newer API evidence.
 const conflictListing=uid(),conflictAt=new Date(Date.now()-86400000).toISOString();await role('postgres');await db.query("insert into public.resale_listings(id,account_id,external_listing_id,title) values($1,$2,'123456789019','Preserved conflict')",[conflictListing,account]);await db.query("insert into public.resale_observations(snapshot_id,account_id,listing_id,observed_at,status) values($1,$2,$3,$4,'reserved'),($1,$2,$3,$4,'ended')",[snap,account,conflictListing,conflictAt]);assert.equal((await db.query('select observed_status from public.resale_listings where id=$1',[conflictListing])).rows[0].observed_status,'unknown');await role('service_role');const conflictRun=uid();await rpc(db,'resale_ebay_start_listing_run',[owner,account,conflictRun]);const conflictRead=await page(conflictRun,[record('123456789019')],1,1);await rpc(db,'resale_ebay_checkpoint_listing_run',[owner,conflictRun,conflictRead.request_id]);
 // Removing the API half of a current tie restores the remaining exact status.
 const latestConflictListing=uid();await role('postgres');await db.query("insert into public.resale_listings(id,account_id,external_listing_id,title) values($1,$2,'123456789020','Latest conflict')",[latestConflictListing,account]);await role('service_role');const latestRun=uid();await rpc(db,'resale_ebay_start_listing_run',[owner,account,latestRun]);const latestRead=await page(latestRun,[record('123456789020')],1,1);await rpc(db,'resale_ebay_checkpoint_listing_run',[owner,latestRun,latestRead.request_id]);await role('postgres');await db.query("insert into public.resale_observations(snapshot_id,account_id,listing_id,observed_at,status) select $1,$2,$3,observed_at,'ended' from public.resale_listings where id=$3",[snap,account,latestConflictListing]);assert.equal((await db.query('select observation_id from public.resale_listings where id=$1',[latestConflictListing])).rows[0].observation_id,null);await role('service_role');
 await rpc(db,'resale_ebay_deletion_receive',[{event_id:'synthetic-seller-deletion',event_at:new Date().toISOString(),subject_eias_sha256:hash('seller'),subject_user_sha256:hash('seller-id'),subject_handle_sha256:hash('seller-name')}]);
 await role('postgres');assert.equal((await db.query("select count(*) n from public.resale_source_records where source_kind='official_api'")).rows[0].n,0);assert.equal((await db.query('select count(*) n from private.resale_ebay_listing_ingests')).rows[0].n,0);assert.equal((await db.query('select observation_id from public.resale_listings where id=$1',[oldListing])).rows[0].observation_id,oldObs);assert.deepEqual((await db.query('select title,desired_fields,draft_context,draft_version,asking_price,match_status,inventory_id from public.resale_listings where id=$1',[oldListing])).rows[0],preserve);assert.equal((await db.query("select count(*) n from public.resale_listings where account_id=$1 and id<>$2 and id<>$3 and id<>$4 and (external_listing_id is not null or title is not null)",[account,oldListing,conflictListing,latestConflictListing])).rows[0].n,0);
 const conflictRestored=(await db.query('select observed_status,observation_id,observed_at from public.resale_listings where id=$1',[conflictListing])).rows[0];assert.equal(conflictRestored.observed_status,'unknown');assert.equal(conflictRestored.observation_id,null);assert.equal(new Date(conflictRestored.observed_at).toISOString(),conflictAt);
 const latestRestored=(await db.query('select observed_status,observation_id from public.resale_listings where id=$1',[latestConflictListing])).rows[0];assert.equal(latestRestored.observed_status,'ended');assert(latestRestored.observation_id);
 console.log('PASS eBay listing run exact retries/owner/cursor/generation, complete non-atomic coverage, partial gaps, immutable exact-ID ingestion, preserved inventory/drafts and scoped seller-source purge');
}catch(e){console.error({code:e.code,message:e.message,where:e.where});process.exitCode=1}finally{await db.close()}
