import { baseline, migrate } from './helpers.mjs'
import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
const db=await baseline()
try {
 await migrate(db)
 const owner=randomUUID(),otherMember=randomUUID(),stranger=randomUUID(),genealogy=randomUUID()
 const account=randomUUID(),otherAccount=randomUUID(),snapshot=randomUUID(),otherSnapshot=randomUUID()
 const item=randomUUID(),secondItem=randomUUID(),sold=randomUUID(),archived=randomUUID(),detailArchived=randomUUID()
 const listing=randomUUID(),secondListing=randomUUID(),draft=randomUUID(),observation=randomUUID(),foreignObservation=randomUUID()
 await db.query('insert into auth.users values($1),($2),($3),($4)',[owner,otherMember,stranger,genealogy])
 await db.query("insert into private.memberships(user_id,area) values($1,'resale'),($2,'resale'),($3,'genealogy')",[owner,otherMember,genealogy])
 await db.query("insert into public.resale_accounts(id,marketplace,account_alias) values($1,'vinted','main'),($2,'vinted','other')",[account,otherAccount])
 for(const [id,acc] of [[snapshot,account],[otherSnapshot,otherAccount]]) await db.query("insert into public.resale_snapshots(id,account_id,source,source_ref,observed_at,scope,coverage) values($1,$2,'manual','synthetic','2026-09-06T03:00:00Z','synthetic','partial')",[id,acc])
 for(const id of [item,secondItem,sold,archived,detailArchived]) await db.query("insert into public.inventory(id,item_name,item_cost) values($1,'Same ambiguous title',null)",[id])
 await db.query("update public.inventory set status='sold' where id=$1",[sold])
 await db.query('update public.inventory set archived_at=now() where id=$1',[archived])
 await db.query("insert into public.resale_item_details(inventory_id,workflow) values($1,'archived')",[detailArchived])
 for(const [id,acc,external] of [[listing,account,'same-external-id'],[secondListing,otherAccount,'same-external-id'],[draft,account,null]]) await db.query("insert into public.resale_listings(id,account_id,external_listing_id,title,match_evidence) values($1,$2,$3,'Same ambiguous title','{\"import\":\"preserve me\"}')",[id,acc,external])
 for(const [id,l,acc,s] of [[observation,listing,account,snapshot],[foreignObservation,secondListing,otherAccount,otherSnapshot]]) await db.query("insert into public.resale_observations(id,listing_id,account_id,snapshot_id,observed_at,status,external_listing_id) values($1,$2,$3,$4,'2026-09-06T03:00:00Z','active','same-external-id')",[id,l,acc,s])
 const role=async(name,id='')=>{await db.exec(`reset role;set role ${name}`);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id])}
 const deny=(fn,code='42501')=>assert.rejects(fn,e=>e.code===code)
 const input={listingId:listing,inventoryId:item,expectedObservationId:observation,expectedInventoryId:null,expectedMatchStatus:'unmatched',reason:'Checked size, color, label and physical item; explicit synthetic decision'}
 const match=async(payload=input,request=randomUUID())=>(await db.query('select * from public.resale_confirm_listing_match($1,$2::jsonb)',[request,JSON.stringify(payload)])).rows[0]
 await role('anon'); await deny(()=>match())
 for(const id of [stranger,genealogy]) {await role('authenticated',id);await deny(()=>match());assert.equal((await db.query('select * from public.resale_listing_match_history')).rows.length,0)}
 await role('authenticated',owner)
 for(const payload of [{...input,reason:' '},{...input,reason:'x'.repeat(2001)},{...input,reason:{}},{...input,secret:{token:'synthetic'}},{...input,expectedInventoryId:undefined},{...input,listingId:null},{...input,expectedMatchStatus:null}]) await deny(()=>match(payload),'22023')
 await deny(()=>match({...input,inventoryId:'not-uuid'}),'22P02')
 await deny(()=>match({...input,inventoryId:randomUUID()}),'P0002')
 for(const id of [sold,archived,detailArchived]) await deny(()=>match({...input,inventoryId:id}),'22023')
 await deny(()=>match({...input,expectedObservationId:foreignObservation}),'40001')
 await deny(()=>match({...input,expectedInventoryId:secondItem}),'40001')
 await deny(()=>match({...input,expectedMatchStatus:'confirmed'}),'40001')
 const request=randomUUID(),result=await match(input,request)
 assert.equal(result.inventory_id,item);assert.equal(result.matched_by,owner);assert.equal(result.match_status,'confirmed')
 assert.equal(result.match_evidence.import,'preserve me')
 assert.equal(result.match_evidence.manual_confirmation.snapshot_id,snapshot)
 assert.equal(result.match_evidence.manual_confirmation.account_id,account)
 assert.deepEqual(await match(input,request),result)
 await deny(()=>match({...input,reason:'Changed decision'},request),'22023')
 await role('authenticated',otherMember);await deny(()=>match(input,request),'22023')
 await role('authenticated',owner)
 const foreign=(await db.query('select * from public.resale_listings where id=$1',[secondListing])).rows[0]
 assert.equal(foreign.inventory_id,null);assert.equal(foreign.match_status,'unmatched')
 await deny(()=>db.query("update public.resale_listings set inventory_id=$1 where id=$2",[secondItem,listing]))
 await deny(()=>db.query("delete from public.resale_listing_match_history"))
 await deny(()=>db.query('select * from private.resale_match_requests'))
 await deny(()=>match({...input,inventoryId:secondItem}),'40001')
 const relink={...input,inventoryId:secondItem,expectedInventoryId:item,expectedMatchStatus:'confirmed',reason:'Reviewed two distinct units; correcting my previous assignment'}
 const relinked=await match(relink)
 assert.equal(relinked.inventory_id,secondItem)
 const history=(await db.query('select * from public.resale_listing_match_history order by created_at,id')).rows
 assert.equal(history.length,2)
 const correction=history.find(h=>h.inventory_id===secondItem)
 assert.equal(correction.prior_match.inventory_id,item)
 assert.deepEqual(correction.prior_match.match_evidence,result.match_evidence)
 assert.deepEqual(await match(input,request),result) // Exact historical response, never reverts newer link.
 assert.equal((await db.query('select inventory_id from public.resale_listings where id=$1',[listing])).rows[0].inventory_id,secondItem)
 const draftResult=await match({...input,listingId:draft,expectedObservationId:null})
 assert.equal(draftResult.external_listing_id,null);assert.equal(draftResult.match_status,'confirmed')
 assert.equal((await db.query('select count(*) from public.sales')).rows[0].count,0)
 assert.equal((await db.query('select count(*) from public.resale_actions')).rows[0].count,0)
 assert.equal((await db.query('select count(*) from public.resale_source_records')).rows[0].count,0)
 assert.equal((await db.query('select status from public.inventory where id=$1',[item])).rows[0].status,'unlisted')
 await role('postgres')
 await deny(()=>db.query("update public.resale_listing_match_history set reason='rewrite'"),'55000')
 await deny(()=>db.query('delete from public.resale_listing_match_history'),'55000')
 const latest=randomUUID()
 await db.query("insert into public.resale_observations(id,listing_id,account_id,snapshot_id,observed_at,status) values($1,$2,$3,$4,'2026-09-06T04:00:00Z','sold')",[latest,listing,account,snapshot])
 await role('authenticated',owner)
 await deny(()=>match({...relink,expectedInventoryId:secondItem}),'40001')
 // A sold listing can be manually linked to an unsold item for review; it does not sell that item.
 const soldListingMatch=await match({...relink,expectedInventoryId:secondItem,expectedObservationId:latest})
 assert.equal(soldListingMatch.observed_status,'sold')
 assert.equal((await db.query('select status from public.inventory where id=$1',[secondItem])).rows[0].status,'unlisted')
 await role('postgres');await db.query("delete from private.memberships where user_id=$1 and area='resale'",[owner])
 await role('authenticated',owner);await deny(()=>match(input,request));assert.equal((await db.query('select * from public.resale_listing_match_history')).rows.length,0)
 console.log('PASS manual match: member revocation, actor/exact retry, bounded payload, stale observation/link/status, account isolation, sold/archive rejection, immutable prior evidence and zero stock/sale/action writes')
} finally {await db.close()}
