import { baseline, migrate } from './helpers.mjs'
import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
const db=await baseline()
try {
 await migrate(db)
 const owner=randomUUID(),other=randomUUID(),account=randomUUID(),accountB=randomUUID(),snapshot=randomUUID(),snapshotB=randomUUID(),source=randomUUID(),sourceB=randomUUID(),item=randomUUID(),listing=randomUUID(),observation=randomUUID()
 await db.query('insert into auth.users values($1),($2)',[owner,other])
 await db.query("insert into private.memberships(user_id,area) values($1,'resale'),($2,'resale')",[owner,other])
 await db.query("insert into public.resale_accounts(id,marketplace,account_alias) values($1,'mercari','main'),($2,'mercari','other')",[account,accountB])
 await db.query("insert into public.resale_snapshots(id,account_id,source,source_ref,observed_at,scope,coverage,record_count) values($1,$2,'export','synthetic',now(),'provided report','complete',1),($3,$4,'export','synthetic-other',now(),'other report','complete',1)",[snapshot,account,snapshotB,accountB])
 await db.query("insert into public.resale_source_records(id,snapshot_id,account_id,record_key,source_kind,event_precision,event_date,raw_business,captured_at,record_status,normalized) values($1,$2,$3,'row1','csv','date','2025-03-18','{}',now(),'accepted','{\"quantity_available\":3,\"order_id\":null}'),($4,$5,$6,'row1','csv','date','2025-03-18','{}',now(),'accepted','{}')",[source,snapshot,account,sourceB,snapshotB,accountB])
 await db.query("insert into public.inventory(id,item_name,item_cost) values($1,'Synthetic unit',null)",[item])
 await db.query("insert into public.resale_item_details(inventory_id) values($1)",[item])
 await db.query("insert into public.resale_listings(id,account_id,inventory_id,external_listing_id,match_status,matched_at,match_evidence,listing_url) values($1,$2,$3,'m123','confirmed',now(),jsonb_build_object('verified',true),'https://www.mercari.com/us/item/m123/')",[listing,account,item])
 await db.query("insert into public.resale_observations(id,account_id,snapshot_id,listing_id,external_listing_id,status,observed_at) values($1,$2,$3,$4,'m123','active',now())",[observation,account,snapshot,listing])
 const baselineMoney=(await db.query('select to_jsonb(i) row from public.inventory i')).rows
 const role=async(name,id='')=>{await db.exec(`reset role;set role ${name}`);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id])}
 const deny=(fn,code='42501')=>assert.rejects(fn,e=>e.code===code)
 const request=async(payload,id)=>{id??=randomUUID();return (await db.query('select public.resale_request_operation($1,$2::jsonb) id',[id,JSON.stringify({...payload,trigger:payload.trigger||{kind:'member_request',id}})])).rows[0].id}
 const base={account_id:account,action:'import',requested:{}}
 const get=async id=>(await db.query('select * from public.resale_operation_view where id=$1',[id])).rows[0]
 await role('authenticated',owner)
 const requestId=randomUUID(),op=await request(base,requestId)
 assert.equal(await request(base,requestId),op)
 assert.equal((await get(op)).execution_mode,'unavailable');assert.equal((await get(op)).state,'blocked')
 assert.equal((await get(op)).listing_id,null)
 await deny(()=>request({...base,requested:{changed:true}},requestId),'22023')
 await deny(()=>request({...base,execution_mode:'api_automatic'}),'22023')
 await role('authenticated',other);await deny(()=>request(base,requestId),'22023')
 await role('authenticated',owner)
 await deny(()=>request({...base,trigger:{kind:'source_record',id:sourceB}}),'22023')
 const outbound={account_id:account,action:'update',listing_id:listing,inventory_id:item,expected_observation_id:observation,expected_item_version:1,requested:{quantity:1,title:'New title'}}
 await deny(()=>request({...outbound,account_id:accountB}),'22023')
 await deny(()=>request({...outbound,expected_observation_id:null}),'40001')
 await deny(()=>request({...outbound,expected_item_version:2}),'40001')
 const update=await request(outbound)
 assert.equal((await get(update)).deep_link,'https://www.mercari.com/us/item/m123/')
 assert((await get(update)).blockers.some(x=>x.code==='quantity_review'))
 await role('postgres')
 for(const url of ['https://www.mercari.com.attacker.test/item/1','https://evil.test/','https://www.mercari.com@evil.test/item/1','https://www.mercari.com/item/1?token=secret','javascript:alert(1)'])
 assert.equal((await db.query("select private.resale_safe_deep_link('mercari',$1) url",[url])).rows[0].url,null)
 await db.query("update inventory set status='sold' where id=$1",[item]);await role('authenticated',owner)
 await deny(()=>request(outbound),'22023')
 await role('postgres');await db.query("update inventory set status='unlisted' where id=$1",[item])
 await role('authenticated',owner)
 const proposalId=randomUUID(),propose=(id,ids,note='I checked the report')=>db.query('select public.resale_submit_operation_evidence($1,$2,$3::jsonb) id',[id,op,JSON.stringify({source_record_ids:ids,note})])
 await propose(proposalId,[source]);await propose(proposalId,[source])
 assert.equal((await get(op)).proposal_count,1)
 await deny(()=>propose(proposalId,[source],'Changed'),'22023')
 await deny(()=>propose(randomUUID(),[sourceB]),'22023')
 await deny(()=>db.query('select public.resale_submit_operation_evidence($1,$2,$3)',[randomUUID(),op,JSON.stringify({source_record_ids:[source],note:'done',state:'succeeded'})]),'22023')
 assert.equal((await get(op)).state,'blocked')
 await deny(()=>db.query("update public.resale_actions set state='succeeded' where id=$1",[op]))
 await deny(()=>db.query('insert into public.resale_operation_verifications default values'))
 await deny(()=>db.query('select * from private.resale_operation_adapters'))
 await deny(()=>db.query('select private.resale_claim_evidence_operation($1)',[op]))
 await role('postgres');await deny(()=>db.query("update public.resale_operation_proposals set note='changed'"),'55000')
 console.log('PASS durable actor-bound retries, nullable evidence targets, immutable proposals, stale bindings, sold-item rejection and allowlisted deep links')

 await role('service_role');await deny(()=>db.query('select private.resale_claim_evidence_operation($1)',[op]),'22023')
 await db.query("insert into private.resale_operation_adapters(account_id,action,adapter_key,adapter_version,execution_mode,ready,reason,required_fields) values($1,'import','synthetic-reviewed-file','1','file_automatic',true,'Synthetic local tested adapter','[\"file_sha256\"]')",[account])
 await deny(()=>db.query('select private.resale_claim_evidence_operation($1)',[op]),'22023')
 await role('authenticated',owner)
 const ready=await request({...base,requested:{file_sha256:'a'.repeat(64)}})
 await role('service_role')
 const run=(await db.query('select * from private.resale_claim_evidence_operation($1)',[ready])).rows[0]
 assert.equal(run.state,'running');assert.equal(run.attempts,1)
 await deny(()=>db.query('select private.resale_claim_evidence_operation($1)',[update]),'22023')
 await deny(()=>db.query('select private.resale_checkpoint_evidence_operation($1,$2,$3,$4,$5)',[ready,run.lease_token,'rows_loaded',[sourceB],[snapshotB]]),'22023')
 await db.query('select private.resale_checkpoint_evidence_operation($1,$2,$3,$4,$5)',[ready,run.lease_token,'rows_loaded',[source],[snapshot]])
 const finish=(kind='verified',ids=[source],snaps=[snapshot],decision='evidence_imported',note='Checked immutable file records')=>db.query('select * from private.resale_finish_evidence_operation($1,$2,$3,$4,$5,$6,$7)',[ready,run.lease_token,kind,ids,snaps,decision,note])
 await deny(()=>finish('verified',[sourceB],[snapshotB]),'22023')
 assert.equal((await finish('accepted',[],[],null,'Import submitted; verify receipt')).rows[0].state,'uncertain')
 await deny(()=>db.query('select private.resale_claim_evidence_operation($1)',[ready]),'22023')
 assert.equal((await finish()).rows[0].state,'succeeded')
 assert.equal((await finish()).rows[0].state,'succeeded')
 await deny(()=>finish('verified',[source],[snapshot],'evidence_imported','Changed proof'),'22023')
 await deny(()=>db.query('delete from public.resale_operation_verifications'))
 await role('authenticated',owner)
 const reconcile=await request({account_id:account,action:'reconcile_sale',trigger:{kind:'source_record',id:source},requested:{}})
 await role('service_role')
 await db.query("insert into private.resale_operation_adapters(account_id,action,adapter_key,adapter_version,execution_mode,ready,reason) values($1,'reconcile_sale','synthetic-evidence','1','file_automatic',true,'Synthetic test only')",[account])
 const reconcileRun=(await db.query('select * from private.resale_claim_evidence_operation($1)',[reconcile])).rows[0]
 const reconcileFinish=decision=>db.query('select * from private.resale_finish_evidence_operation($1,$2,$3,$4,$5,$6,$7)',[reconcile,reconcileRun.lease_token,'verified',[source],[snapshot],decision,'Missing actual order identity and quantity3 require review'])
 await deny(()=>reconcileFinish('verified_source_event'),'22023')
 assert.equal((await reconcileFinish('needs_review')).rows[0].state,'blocked')
 assert.equal((await reconcileFinish('needs_review')).rows[0].state,'blocked')
 await deny(()=>db.query('select private.resale_claim_evidence_operation($1)',[reconcile]),'22023')
 assert.equal((await db.query('select count(*) from public.resale_review_cases')).rows[0].count,1)
 assert.deepEqual((await db.query('select to_jsonb(i) row from public.inventory i')).rows,baselineMoney)
 assert.equal((await db.query('select count(*) from public.sales')).rows[0].count,0)
 assert.equal((await db.query('select count(*) from public.resale_order_events')).rows[0].count,0)
 assert.equal((await db.query('select count(*) from public.resale_order_lines')).rows[0].count,0)
 console.log('PASS trusted adapter readiness, required fields, leases, checkpoints, uncertain readback, exact proof retries and unresolved identity/quantity review without canonical mutations')

 await role('postgres');await db.query('update public.inventory set item_cost=0 where id=$1',[item])
 await role('authenticated',owner)
 const sale=(await db.query('select * from public.save_sale($1,$2::jsonb)',[randomUUID(),JSON.stringify({inventory_id:item,platform:'Mercari',sale_date:'2026-09-06',sale_price:30,platform_fee:5,item_cost:0,shipping_cost:0})])).rows[0]
 const saleEvidence=await request({...base,inventory_id:item,trigger:{kind:'sale',id:sale.id}})
 await db.query('select * from public.save_sale($1,$2::jsonb)',[randomUUID(),JSON.stringify({id:sale.id,version:1,void:true,reason:'Synthetic void regression'})])
 assert.equal((await get(saleEvidence)).state,'blocked')
 assert((await db.query("select state from resale_actions where sale_id=$1 and action='delist'",[sale.id])).rows.every(x=>x.state==='cancelled'))
 console.log('PASS sale void cancels original delist work without cancelling incoming evidence tasks')

 await role('authenticated',owner)
 const expiring=await request({...base,requested:{file_sha256:'b'.repeat(64)}})
 await role('service_role');await db.query('select private.resale_claim_evidence_operation($1)',[expiring])
 await db.query("update public.resale_actions set lease_expires_at=now()-interval '1 minute' where id=$1",[expiring])
 // Old delist runner must not expire, claim, or otherwise alter unrelated work.
 await db.query('select private.resale_claim_delist()')
 assert.equal((await get(expiring)).state,'running')
 assert.equal((await db.query('select * from private.resale_claim_evidence_operation($1)',[expiring])).rows[0].state,'uncertain')
 await deny(()=>db.query('select private.resale_claim_evidence_operation($1)',[expiring]),'22023')
 await role('postgres');await db.query("delete from private.memberships where user_id=$1",[owner])
 await role('authenticated',owner)
 assert.equal((await db.query('select * from public.resale_operation_view')).rows.length,0)
 await deny(()=>request(base,requestId));await deny(()=>propose(randomUUID(),[source]))
 await role('service_role');await deny(()=>db.query('select private.resale_claim_evidence_operation($1)',[op]))
 await role('anon');await deny(()=>db.query('select * from public.resale_operation_view'));await deny(()=>request(base))
 console.log('PASS dispatcher isolation, expired leases never blindly retry, immediate revocation and signed-out denial')
} finally { await db.close() }
