import {randomBytes} from 'node:crypto';
import {SCOPE,CALLBACK,DELETION,EbayError,hash,bounded,identity,listingPage,orderPage,tradingBody,signatureHeader,verifyNotification} from './provider.mjs';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,token=/^[A-Za-z0-9_-]{43}$/;
const json=(v,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'}});
function config(c){if(!c||c.callback!==CALLBACK||c.deletion_endpoint!==DELETION||c.expected_handle!=='paulbr-89'||typeof c.client_id!=='string'||!c.client_id||typeof c.runame!=='string'||!c.runame||!/^\d{3,4}$/.test(c.trading_version||''))throw new EbayError('setup_required',409);return c;}
function access(t){if(typeof t.access_token!=='string'||!t.access_token||t.access_token.length>8192||!['User Access Token','Application Access Token'].includes(t.token_type)||!Number.isSafeInteger(t.expires_in)||t.expires_in<1)throw new EbayError('invalid_token_response');if(t.scope!==undefined&&t.scope!==SCOPE)throw new EbayError('scope_mismatch',403);return t.access_token;}
export function createServices(env,fetcher=fetch){
 const base=env.SUPABASE_URL,admin=env.SUPABASE_SECRET_KEYS?JSON.parse(env.SUPABASE_SECRET_KEYS).default:env.SUPABASE_SERVICE_ROLE_KEY,pub=env.SUPABASE_PUBLISHABLE_KEYS?JSON.parse(env.SUPABASE_PUBLISHABLE_KEYS).default:env.SUPABASE_ANON_KEY;
 if(!/^https:\/\/[a-z0-9]+\.supabase\.co$/.test(base||'')||!admin||!pub)throw Error('Supabase configuration unavailable');
 async function request(url,options={},limit=1048576,xml=false){let response;try{response=await fetcher(url,{...options,redirect:'manual',signal:AbortSignal.timeout(12000)});}catch{throw new EbayError('network_error');}if(response.status===204&&url.startsWith(base+'/rest/v1/rpc/'))return null;let raw;try{raw=await bounded(response,limit);}catch{throw new EbayError('response_unreadable');}if(!response.ok){if(response.status===429)throw new EbayError('rate_limited',429);if(response.status===401||response.status===403)throw new EbayError('access_denied',403);throw new EbayError('request_rejected',409);}if(xml)return raw;try{return JSON.parse(raw);}catch{throw new EbayError('invalid_response');}}
 const rpc=async(name,args)=>request(`${base}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:admin,...(!admin.startsWith('sb_')?{Authorization:`Bearer ${admin}`}:{ }),'Content-Type':'application/json'},body:JSON.stringify(args)});
 const ebayToken=async(c,values)=>request('https://api.ebay.com/identity/v1/oauth2/token',{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${c.client_id}:${c.client_secret}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(values)},32768);
 const keys=new Map();
 return {rpc,
  async user(bearer){if(!/^Bearer [^\s]+$/.test(bearer||''))throw new EbayError('sign_in_required',401);const user=await request(`${base}/auth/v1/user`,{headers:{apikey:pub,Authorization:bearer}},32768);if(!uuid.test(user.id||''))throw new EbayError('sign_in_required',401);return user.id;},
  ebayToken,
  async trading(c,bearer,call,args){return request('https://api.ebay.com/ws/api.dll',{method:'POST',headers:{'X-EBAY-API-IAF-TOKEN':bearer,'X-EBAY-API-CALL-NAME':call,'X-EBAY-API-COMPATIBILITY-LEVEL':c.trading_version,'X-EBAY-API-SITEID':'0','Content-Type':'text/xml'},body:tradingBody(call,args)},2*1024*1024,true);},
  async publicKey(c,kid){const cached=keys.get(kid);if(cached&&cached.until>Date.now())return cached.value;const app=access(await ebayToken(c,{grant_type:'client_credentials',scope:SCOPE}));const value=await request(`https://api.ebay.com/commerce/notification/v1/public_key/${encodeURIComponent(kid)}`,{headers:{Authorization:`Bearer ${app}`}},8192);if(value.algorithm!=='ECDSA'||value.digest!=='SHA1'||typeof value.key!=='string')throw new EbayError('unsupported_public_key',412);if(keys.size>=16)keys.delete(keys.keys().next().value);keys.set(kid,{until:Date.now()+3600000,value});return value;},
 };
}
export async function start(input,bearer,s){if(!uuid.test(input.account_id||'')||!token.test(input.browser_binding||''))throw new EbayError('invalid_request',400);const member=await s.user(bearer),state=randomBytes(32).toString('base64url'),c=config(await s.rpc('resale_ebay_oauth_start',{p_member_id:member,p_account_id:input.account_id,p_state_hash:hash(state),p_browser_hash:hash(input.browser_binding)}));const query=new URLSearchParams({client_id:c.client_id,redirect_uri:c.runame,response_type:'code',scope:SCOPE,state});return {authorization_url:`https://auth.ebay.com/oauth2/authorize?${query}`};}
export async function callback(input,s){if(!token.test(input.state||'')||!token.test(input.browser_binding||'')||(!input.error&&(typeof input.code!=='string'||!input.code||input.code.length>4096)))throw new EbayError('invalid_callback',400);const c=config(await s.rpc('resale_ebay_oauth_consume',{p_state_hash:hash(input.state),p_browser_hash:hash(input.browser_binding)}));if(input.error)return {status:'cancelled'};const t=await s.ebayToken(c,{grant_type:'authorization_code',code:input.code,redirect_uri:c.runame}),bearer=access(t);
 if(t.token_type!=='User Access Token'||typeof t.refresh_token!=='string'||!t.refresh_token||t.refresh_token.length>8192||!Number.isSafeInteger(t.refresh_token_expires_in)||t.refresh_token_expires_in<60)throw new EbayError('invalid_token_response');
 const seller=identity(await s.trading(c,bearer,'GetUser'));
 if(seller.handle.toLowerCase()!==c.expected_handle||(c.seller_eias_sha256&&hash(seller.eias_token)!==c.seller_eias_sha256))throw new EbayError('wrong_seller',403);
 return s.rpc('resale_ebay_oauth_complete',{p_state_id:c.state_id,p_handle:seller.handle,p_eias_hash:hash(seller.eias_token),p_refresh_token:t.refresh_token,p_refresh_seconds:t.refresh_token_expires_in});
}
export async function read(input,bearer,s){if(!uuid.test(input.account_id||'')||!uuid.test(input.request_id||'')||!['listings','orders'].includes(input.kind)||!Number.isSafeInteger(input.page)||input.page<1||input.page>100)throw new EbayError('invalid_read',400);const member=await s.user(bearer),claim=await s.rpc('resale_ebay_claim_read',{p_member_id:member,p_account_id:input.account_id,p_request_id:input.request_id,p_kind:input.kind,p_page:input.page,p_from:input.from||null,p_to:input.to||null});if(claim.cached)return claim.result;const c=config(claim),args={p_member_id:member,p_request_id:input.request_id,p_lease:claim.lease};
 try{const t=await s.ebayToken(c,{grant_type:'refresh_token',refresh_token:c.refresh_token,scope:SCOPE}),a=access(t);if(t.token_type!=='User Access Token'||(t.refresh_token&&t.refresh_token!==c.refresh_token))throw new EbayError('reconnect_required',409);const seller=identity(await s.trading(c,a,'GetUser'));if(hash(seller.eias_token)!==c.seller_eias_sha256||seller.handle.toLowerCase()!==c.expected_handle)throw new EbayError('wrong_seller',403);
 const raw=await s.trading(c,a,input.kind==='listings'?'GetMyeBaySelling':'GetOrders',{page:input.page,from:claim.window_from,to:claim.window_to}),parsed=input.kind==='listings'?listingPage(raw,input.page):orderPage(raw,input.page,{eias_sha256:c.seller_eias_sha256,handle:seller.handle});
 // Only allowlisted business fields are persisted. Raw XML, buyer and address data stay transient.
 return await s.rpc('resale_ebay_finish_read',{...args,p_result:{...parsed,source_sha256:hash(raw),window_from:claim.window_from,window_to:claim.window_to},p_error:null});
 }catch(e){const code=e instanceof EbayError?e.code:'read_failed';await s.rpc('resale_ebay_finish_read',{...args,p_result:null,p_error:code});throw new EbayError(code,409);}
}
export async function deletion(input,s){const c=await s.rpc('resale_ebay_deletion_config',{});if(c.deletion_endpoint!==DELETION)throw new EbayError('setup_required',409);if(input.challenge_code!==undefined){if(!/^[A-Za-z0-9_-]{1,200}$/.test(input.challenge_code)||!/^[A-Za-z0-9_-]{32,80}$/.test(c.verification_token||''))throw new EbayError('invalid_challenge',400);return {challengeResponse:hash(input.challenge_code+c.verification_token+DELETION)};}
 const signature=signatureHeader(input.signature),notice=verifyNotification(input.message,signature,await s.publicKey(c,signature.kid));
 await s.rpc('resale_ebay_deletion_receive',{p_notice:notice});return {status:'received',erasure:'review_pending'};
}
export function createHandler(s){return async request=>{try{if(request.method!=='POST')return json({error:'method_not_allowed'},405);const input=JSON.parse(await bounded(request,65536));if(input.op==='start')return json(await start(input,request.headers.get('Authorization'),s));if(input.op==='callback')return json(await callback(input,s));if(input.op==='read')return json(await read(input,request.headers.get('Authorization'),s));if(input.op==='deletion')return json(await deletion(input,s));throw new EbayError('unsupported_operation',400);}catch(e){return json({error:e instanceof EbayError?e.code:'request_failed'},e instanceof EbayError?e.status:503);}};}
